// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeAIProvider = `-- name: ActiveAIProvider :one
SELECT id, name, type, endpoint_url, api_key, model, temperature
FROM ai_providers
WHERE is_active = TRUE
ORDER BY is_default DESC, created_at ASC
LIMIT 1
`

type ActiveAIProviderRow struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	Name        string              `db:"name" json:"name"`
	Type        AiProvidersTypeEnum `db:"type" json:"type"`
	EndpointUrl string              `db:"endpoint_url" json:"endpoint_url"`
	ApiKey      string              `db:"api_key" json:"api_key"`
	Model       string              `db:"model" json:"model"`
	Temperature pgtype.Numeric      `db:"temperature" json:"temperature"`
}

// Selects the active default AI provider. NestJS picks the same row in
// AiProvidersService.findActive — keep the ORDER BY in sync there + here
// (is_default DESC, is_active = TRUE).
func (q *Queries) ActiveAIProvider(ctx context.Context) (ActiveAIProviderRow, error) {
	row := q.db.QueryRow(ctx, activeAIProvider)
	var i ActiveAIProviderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.EndpointUrl,
		&i.ApiKey,
		&i.Model,
		&i.Temperature,
	)
	return i, err
}

const countTodayUsage = `-- name: CountTodayUsage :one
SELECT COUNT(*)::bigint AS used
FROM usage_logs
WHERE user_id = $1
  AND created_at::date = CURRENT_DATE
`

// Today's daily-quota tally for the user. Compared against
// plan.daily_limit in the application layer (so the limit can come
// from a fallback when the user has no subscription).
func (q *Queries) CountTodayUsage(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayUsage, userID)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const findUserWithPlan = `-- name: FindUserWithPlan :one

SELECT
    u.id          AS user_id,
    u.email       AS user_email,
    u.role        AS user_role,
    p.id          AS plan_id,
    p.name        AS plan_name,
    p.daily_limit AS plan_daily_limit
FROM users u
LEFT JOIN subscriptions s
    ON s.user_id = u.id
    AND s.status = 'active'
    AND (s.expires_at IS NULL OR s.expires_at > NOW())
LEFT JOIN plans p ON p.id = s.plan_id
WHERE u.id = $1
LIMIT 1
`

type FindUserWithPlanRow struct {
	UserID         pgtype.UUID   `db:"user_id" json:"user_id"`
	UserEmail      string        `db:"user_email" json:"user_email"`
	UserRole       UsersRoleEnum `db:"user_role" json:"user_role"`
	PlanID         pgtype.UUID   `db:"plan_id" json:"plan_id"`
	PlanName       *string       `db:"plan_name" json:"plan_name"`
	PlanDailyLimit *int32        `db:"plan_daily_limit" json:"plan_daily_limit"`
}

// Queries for the /rewrite microservice's Postgres adapter.
// sqlc compiles these against schema.sql at build time; mistakes are
// caught BEFORE the service ever boots (Rule #1 — compile-time over
// runtime).
//
// Each query has three sqlc directives:
//
//	:one  → returns exactly one row (errors if zero)
//	:many → returns a slice of rows
//	:exec → no rows; returns affected-row count
//
// Naming convention: <Verb><Subject>, mirrors Go function names sqlc
// generates (FindUserWithPlan, IncrementUsageToday, …).
// Resolves user + their active subscription's plan in one query so the
// quota check is a single round-trip. LEFT JOIN because users without
// an active subscription fall back to the free tier (plan_id NULL).
// Filter on subscriptions.status = 'active' so cancelled subs don't
// still grant their old plan.
func (q *Queries) FindUserWithPlan(ctx context.Context, id pgtype.UUID) (FindUserWithPlanRow, error) {
	row := q.db.QueryRow(ctx, findUserWithPlan, id)
	var i FindUserWithPlanRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserRole,
		&i.PlanID,
		&i.PlanName,
		&i.PlanDailyLimit,
	)
	return i, err
}

const insertUsageLog = `-- name: InsertUsageLog :exec
INSERT INTO usage_logs
    (user_id, tone, input_length, output_length, ai_provider_id, response_time_ms)
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type InsertUsageLogParams struct {
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	Tone           string      `db:"tone" json:"tone"`
	InputLength    int32       `db:"input_length" json:"input_length"`
	OutputLength   int32       `db:"output_length" json:"output_length"`
	AiProviderID   pgtype.UUID `db:"ai_provider_id" json:"ai_provider_id"`
	ResponseTimeMs int32       `db:"response_time_ms" json:"response_time_ms"`
}

// Records one /rewrite call for daily quota tracking + analytics.
// Mirrors NestJS UsageService.log: same columns, same names, same
// precision so the two backends populate identical rows.
func (q *Queries) InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) error {
	_, err := q.db.Exec(ctx, insertUsageLog,
		arg.UserID,
		arg.Tone,
		arg.InputLength,
		arg.OutputLength,
		arg.AiProviderID,
		arg.ResponseTimeMs,
	)
	return err
}
