// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiProvidersTypeEnum string

const (
	AiProvidersTypeEnumOpenai    AiProvidersTypeEnum = "openai"
	AiProvidersTypeEnumAnthropic AiProvidersTypeEnum = "anthropic"
	AiProvidersTypeEnumOllama    AiProvidersTypeEnum = "ollama"
	AiProvidersTypeEnumCustom    AiProvidersTypeEnum = "custom"
)

func (e *AiProvidersTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiProvidersTypeEnum(s)
	case string:
		*e = AiProvidersTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AiProvidersTypeEnum: %T", src)
	}
	return nil
}

type NullAiProvidersTypeEnum struct {
	AiProvidersTypeEnum AiProvidersTypeEnum `json:"ai_providers_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if AiProvidersTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiProvidersTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AiProvidersTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiProvidersTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiProvidersTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiProvidersTypeEnum), nil
}

type PlansBillingPeriodEnum string

const (
	PlansBillingPeriodEnumNone    PlansBillingPeriodEnum = "none"
	PlansBillingPeriodEnumMonthly PlansBillingPeriodEnum = "monthly"
	PlansBillingPeriodEnumYearly  PlansBillingPeriodEnum = "yearly"
)

func (e *PlansBillingPeriodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlansBillingPeriodEnum(s)
	case string:
		*e = PlansBillingPeriodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PlansBillingPeriodEnum: %T", src)
	}
	return nil
}

type NullPlansBillingPeriodEnum struct {
	PlansBillingPeriodEnum PlansBillingPeriodEnum `json:"plans_billing_period_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if PlansBillingPeriodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlansBillingPeriodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PlansBillingPeriodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlansBillingPeriodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlansBillingPeriodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlansBillingPeriodEnum), nil
}

type SubscriptionsStatusEnum string

const (
	SubscriptionsStatusEnumActive    SubscriptionsStatusEnum = "active"
	SubscriptionsStatusEnumCancelled SubscriptionsStatusEnum = "cancelled"
	SubscriptionsStatusEnumExpired   SubscriptionsStatusEnum = "expired"
)

func (e *SubscriptionsStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionsStatusEnum(s)
	case string:
		*e = SubscriptionsStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionsStatusEnum: %T", src)
	}
	return nil
}

type NullSubscriptionsStatusEnum struct {
	SubscriptionsStatusEnum SubscriptionsStatusEnum `json:"subscriptions_status_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if SubscriptionsStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionsStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionsStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionsStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionsStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionsStatusEnum), nil
}

type SubscriptionsStoreTypeEnum string

const (
	SubscriptionsStoreTypeEnumGooglePlay   SubscriptionsStoreTypeEnum = "google_play"
	SubscriptionsStoreTypeEnumAppleIap     SubscriptionsStoreTypeEnum = "apple_iap"
	SubscriptionsStoreTypeEnumAdminGranted SubscriptionsStoreTypeEnum = "admin_granted"
	SubscriptionsStoreTypeEnumLemonsqueezy SubscriptionsStoreTypeEnum = "lemonsqueezy"
	SubscriptionsStoreTypeEnumStripe       SubscriptionsStoreTypeEnum = "stripe"
	SubscriptionsStoreTypeEnumVietqr       SubscriptionsStoreTypeEnum = "vietqr"
	SubscriptionsStoreTypeEnumBankTransfer SubscriptionsStoreTypeEnum = "bank_transfer"
	SubscriptionsStoreTypeEnumPaypal       SubscriptionsStoreTypeEnum = "paypal"
)

func (e *SubscriptionsStoreTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionsStoreTypeEnum(s)
	case string:
		*e = SubscriptionsStoreTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionsStoreTypeEnum: %T", src)
	}
	return nil
}

type NullSubscriptionsStoreTypeEnum struct {
	SubscriptionsStoreTypeEnum SubscriptionsStoreTypeEnum `json:"subscriptions_store_type_enum"`
	Valid                      bool                       `json:"valid"` // Valid is true if SubscriptionsStoreTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionsStoreTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionsStoreTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionsStoreTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionsStoreTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionsStoreTypeEnum), nil
}

type UsersAuthProviderEnum string

const (
	UsersAuthProviderEnumLocal    UsersAuthProviderEnum = "local"
	UsersAuthProviderEnumGoogle   UsersAuthProviderEnum = "google"
	UsersAuthProviderEnumFacebook UsersAuthProviderEnum = "facebook"
	UsersAuthProviderEnumTiktok   UsersAuthProviderEnum = "tiktok"
	UsersAuthProviderEnumApple    UsersAuthProviderEnum = "apple"
)

func (e *UsersAuthProviderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersAuthProviderEnum(s)
	case string:
		*e = UsersAuthProviderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersAuthProviderEnum: %T", src)
	}
	return nil
}

type NullUsersAuthProviderEnum struct {
	UsersAuthProviderEnum UsersAuthProviderEnum `json:"users_auth_provider_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if UsersAuthProviderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersAuthProviderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UsersAuthProviderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersAuthProviderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersAuthProviderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersAuthProviderEnum), nil
}

type UsersRoleEnum string

const (
	UsersRoleEnumUser UsersRoleEnum = "user"
)

func (e *UsersRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRoleEnum(s)
	case string:
		*e = UsersRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRoleEnum: %T", src)
	}
	return nil
}

type NullUsersRoleEnum struct {
	UsersRoleEnum UsersRoleEnum `json:"users_role_enum"`
	Valid         bool          `json:"valid"` // Valid is true if UsersRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRoleEnum), nil
}

type AdminUser struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	Name         string           `db:"name" json:"name"`
	IsActive     bool             `db:"is_active" json:"is_active"`
	Role         string           `db:"role" json:"role"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type AdminUserAuditLog struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ActorAdminID  pgtype.UUID        `db:"actor_admin_id" json:"actor_admin_id"`
	ActorEmail    string             `db:"actor_email" json:"actor_email"`
	TargetAdminID pgtype.UUID        `db:"target_admin_id" json:"target_admin_id"`
	TargetEmail   string             `db:"target_email" json:"target_email"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AiProvider struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	Name        string              `db:"name" json:"name"`
	Type        AiProvidersTypeEnum `db:"type" json:"type"`
	EndpointUrl string              `db:"endpoint_url" json:"endpoint_url"`
	ApiKey      string              `db:"api_key" json:"api_key"`
	Model       string              `db:"model" json:"model"`
	Temperature pgtype.Numeric      `db:"temperature" json:"temperature"`
	IsDefault   bool                `db:"is_default" json:"is_default"`
	IsActive    bool                `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamp    `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp    `db:"updated_at" json:"updated_at"`
}

type AppRelease struct {
	Platform     string             `db:"platform" json:"platform"`
	Version      string             `db:"version" json:"version"`
	DownloadUrl  string             `db:"download_url" json:"download_url"`
	Sha256       string             `db:"sha256" json:"sha256"`
	ReleaseNotes string             `db:"release_notes" json:"release_notes"`
	Required     bool               `db:"required" json:"required"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Channel      string             `db:"channel" json:"channel"`
	Enabled      bool               `db:"enabled" json:"enabled"`
}

type AppReleasePolicy struct {
	Platform    string             `db:"platform" json:"platform"`
	Preferred   string             `db:"preferred" json:"preferred"`
	StoreStatus string             `db:"store_status" json:"store_status"`
	Notes       string             `db:"notes" json:"notes"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppSetting struct {
	ID                         pgtype.UUID      `db:"id" json:"id"`
	Environment                string           `db:"environment" json:"environment"`
	TrialLimit                 int32            `db:"trial_limit" json:"trial_limit"`
	TokenExpiryMinutes         int32            `db:"token_expiry_minutes" json:"token_expiry_minutes"`
	MaxInputLength             int32            `db:"max_input_length" json:"max_input_length"`
	SupportedLanguages         string           `db:"supported_languages" json:"supported_languages"`
	StripeSecretKey            string           `db:"stripe_secret_key" json:"stripe_secret_key"`
	StripeWebhookSecret        string           `db:"stripe_webhook_secret" json:"stripe_webhook_secret"`
	PaypalClientID             string           `db:"paypal_client_id" json:"paypal_client_id"`
	PaypalClientSecret         string           `db:"paypal_client_secret" json:"paypal_client_secret"`
	PaypalMode                 string           `db:"paypal_mode" json:"paypal_mode"`
	MomoPartnerCode            string           `db:"momo_partner_code" json:"momo_partner_code"`
	MomoAccessKey              string           `db:"momo_access_key" json:"momo_access_key"`
	MomoSecretKey              string           `db:"momo_secret_key" json:"momo_secret_key"`
	MomoMode                   string           `db:"momo_mode" json:"momo_mode"`
	VietqrBankID               string           `db:"vietqr_bank_id" json:"vietqr_bank_id"`
	VietqrAccountNumber        string           `db:"vietqr_account_number" json:"vietqr_account_number"`
	VietqrAccountName          string           `db:"vietqr_account_name" json:"vietqr_account_name"`
	CassoApiKey                string           `db:"casso_api_key" json:"casso_api_key"`
	SepayApiKey                string           `db:"sepay_api_key" json:"sepay_api_key"`
	GoogleClientID             string           `db:"google_client_id" json:"google_client_id"`
	GoogleClientSecret         string           `db:"google_client_secret" json:"google_client_secret"`
	AppleClientID              string           `db:"apple_client_id" json:"apple_client_id"`
	AppleTeamID                string           `db:"apple_team_id" json:"apple_team_id"`
	AppleKeyID                 string           `db:"apple_key_id" json:"apple_key_id"`
	UpdatedAt                  pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	RefreshTokenExpiryDays     int32            `db:"refresh_token_expiry_days" json:"refresh_token_expiry_days"`
	StripeMode                 string           `db:"stripe_mode" json:"stripe_mode"`
	SepayMode                  string           `db:"sepay_mode" json:"sepay_mode"`
	ResendApiKey               string           `db:"resend_api_key" json:"resend_api_key"`
	EmailFrom                  string           `db:"email_from" json:"email_from"`
	ClientLogLevel             string           `db:"client_log_level" json:"client_log_level"`
	PaymentMethodsEnabled      string           `db:"payment_methods_enabled" json:"payment_methods_enabled"`
	LemonsqueezyApiKey         string           `db:"lemonsqueezy_api_key" json:"lemonsqueezy_api_key"`
	LemonsqueezyStoreID        string           `db:"lemonsqueezy_store_id" json:"lemonsqueezy_store_id"`
	LemonsqueezyWebhookSecret  string           `db:"lemonsqueezy_webhook_secret" json:"lemonsqueezy_webhook_secret"`
	LemonsqueezyVariantMonthly string           `db:"lemonsqueezy_variant_monthly" json:"lemonsqueezy_variant_monthly"`
	LemonsqueezyVariantYearly  string           `db:"lemonsqueezy_variant_yearly" json:"lemonsqueezy_variant_yearly"`
	PaypalWebhookID            string           `db:"paypal_webhook_id" json:"paypal_webhook_id"`
	PaypalPlanMonthly          string           `db:"paypal_plan_monthly" json:"paypal_plan_monthly"`
	PaypalPlanYearly           string           `db:"paypal_plan_yearly" json:"paypal_plan_yearly"`
}

type BugReport struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Source             string             `db:"source" json:"source"`
	Description        string             `db:"description" json:"description"`
	ScreenshotPath     *string            `db:"screenshot_path" json:"screenshot_path"`
	ScreenshotFilename *string            `db:"screenshot_filename" json:"screenshot_filename"`
	AppVersion         *string            `db:"app_version" json:"app_version"`
	OsInfo             *string            `db:"os_info" json:"os_info"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	UserEmail          *string            `db:"user_email" json:"user_email"`
	Context            []byte             `db:"context" json:"context"`
	Status             *string            `db:"status" json:"status"`
	AdminNotes         *string            `db:"admin_notes" json:"admin_notes"`
	CreatedAt          pgtype.Timestamp   `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp   `db:"updated_at" json:"updated_at"`
	AiFixProposal      *string            `db:"ai_fix_proposal" json:"ai_fix_proposal"`
	AiFixProposedAt    pgtype.Timestamptz `db:"ai_fix_proposed_at" json:"ai_fix_proposed_at"`
	Kind               string             `db:"kind" json:"kind"`
	Title              *string            `db:"title" json:"title"`
	TargetPlatform     *string            `db:"target_platform" json:"target_platform"`
	VoteCount          int32              `db:"vote_count" json:"vote_count"`
	IsPublic           bool               `db:"is_public" json:"is_public"`
	DisplayNo          int64              `db:"display_no" json:"display_no"`
}

type EmailLog struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ToEmail    string             `db:"to_email" json:"to_email"`
	EmailType  string             `db:"email_type" json:"email_type"`
	Subject    string             `db:"subject" json:"subject"`
	Status     string             `db:"status" json:"status"`
	ProviderID *string            `db:"provider_id" json:"provider_id"`
	Error      *string            `db:"error" json:"error"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmailSuppression struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Reason    *string            `db:"reason" json:"reason"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmailTemplate struct {
	TemplateKey string             `db:"template_key" json:"template_key"`
	Subject     string             `db:"subject" json:"subject"`
	Html        string             `db:"html" json:"html"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ErrorReport struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Platform      string             `db:"platform" json:"platform"`
	AppVersion    *string            `db:"app_version" json:"app_version"`
	Severity      string             `db:"severity" json:"severity"`
	ErrorType     *string            `db:"error_type" json:"error_type"`
	Message       *string            `db:"message" json:"message"`
	StackTrace    *string            `db:"stack_trace" json:"stack_trace"`
	Context       []byte             `db:"context" json:"context"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	DeviceID      *string            `db:"device_id" json:"device_id"`
	Fingerprint   string             `db:"fingerprint" json:"fingerprint"`
	Count         int32              `db:"count" json:"count"`
	Status        int32              `db:"status" json:"status"`
	AiFixProposal *string            `db:"ai_fix_proposal" json:"ai_fix_proposal"`
	ResolvedBy    *string            `db:"resolved_by" json:"resolved_by"`
	ResolvedAt    pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	FirstSeenAt   pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt    pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	DisplayNo     int64              `db:"display_no" json:"display_no"`
}

type ExtensionToken struct {
	ID         pgtype.UUID      `db:"id" json:"id"`
	UserID     pgtype.UUID      `db:"user_id" json:"user_id"`
	TokenHash  string           `db:"token_hash" json:"token_hash"`
	Scopes     []string         `db:"scopes" json:"scopes"`
	DeviceID   pgtype.UUID      `db:"device_id" json:"device_id"`
	DeviceName string           `db:"device_name" json:"device_name"`
	LastUsedAt pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	RevokedAt  pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
}

type FeatureVote struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	FeatureID pgtype.UUID        `db:"feature_id" json:"feature_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Payment struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	UserID        pgtype.UUID      `db:"user_id" json:"user_id"`
	PlanID        pgtype.UUID      `db:"plan_id" json:"plan_id"`
	Amount        int32            `db:"amount" json:"amount"`
	Currency      string           `db:"currency" json:"currency"`
	Method        string           `db:"method" json:"method"`
	Status        string           `db:"status" json:"status"`
	ProviderRef   *string          `db:"provider_ref" json:"provider_ref"`
	ReferenceCode string           `db:"reference_code" json:"reference_code"`
	QrData        *string          `db:"qr_data" json:"qr_data"`
	Notes         *string          `db:"notes" json:"notes"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CompletedAt   pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Plan struct {
	ID            pgtype.UUID            `db:"id" json:"id"`
	Name          string                 `db:"name" json:"name"`
	DailyLimit    int32                  `db:"daily_limit" json:"daily_limit"`
	PriceCents    int32                  `db:"price_cents" json:"price_cents"`
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	IsActive      bool                   `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
	Currency      *string                `db:"currency" json:"currency"`
	StripePriceID *string                `db:"stripe_price_id" json:"stripe_price_id"`
	TrialDays     int32                  `db:"trial_days" json:"trial_days"`
}

type RewriteLog struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	Tone           string           `db:"tone" json:"tone"`
	InputText      string           `db:"input_text" json:"input_text"`
	OutputText     string           `db:"output_text" json:"output_text"`
	Model          string           `db:"model" json:"model"`
	ProviderType   string           `db:"provider_type" json:"provider_type"`
	ResponseTimeMs int32            `db:"response_time_ms" json:"response_time_ms"`
	Quality        string           `db:"quality" json:"quality"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Subscription struct {
	ID                 pgtype.UUID                `db:"id" json:"id"`
	UserID             pgtype.UUID                `db:"user_id" json:"user_id"`
	PlanID             pgtype.UUID                `db:"plan_id" json:"plan_id"`
	Status             SubscriptionsStatusEnum    `db:"status" json:"status"`
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
	StartedAt          pgtype.Timestamp           `db:"started_at" json:"started_at"`
	ExpiresAt          pgtype.Timestamp           `db:"expires_at" json:"expires_at"`
	CreatedAt          pgtype.Timestamp           `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp           `db:"updated_at" json:"updated_at"`
}

type UsageLog struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	UserID         pgtype.UUID      `db:"user_id" json:"user_id"`
	Tone           string           `db:"tone" json:"tone"`
	InputLength    int32            `db:"input_length" json:"input_length"`
	OutputLength   int32            `db:"output_length" json:"output_length"`
	AiProviderID   pgtype.UUID      `db:"ai_provider_id" json:"ai_provider_id"`
	ResponseTimeMs int32            `db:"response_time_ms" json:"response_time_ms"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID                       pgtype.UUID           `db:"id" json:"id"`
	Email                    string                `db:"email" json:"email"`
	PasswordHash             *string               `db:"password_hash" json:"password_hash"`
	Name                     string                `db:"name" json:"name"`
	IsActive                 bool                  `db:"is_active" json:"is_active"`
	Role                     UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider             UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	GoogleID                 *string               `db:"google_id" json:"google_id"`
	FacebookID               *string               `db:"facebook_id" json:"facebook_id"`
	TiktokID                 *string               `db:"tiktok_id" json:"tiktok_id"`
	AvatarUrl                *string               `db:"avatar_url" json:"avatar_url"`
	CreatedAt                pgtype.Timestamp      `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamp      `db:"updated_at" json:"updated_at"`
	EmailVerified            bool                  `db:"email_verified" json:"email_verified"`
	EmailVerificationCode    *string               `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz    `db:"email_verification_expires" json:"email_verification_expires"`
	LemonsqueezyCustomerID   *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	StripeCustomerID         *string               `db:"stripe_customer_id" json:"stripe_customer_id"`
	AppleID                  *string               `db:"apple_id" json:"apple_id"`
	PasswordResetCode        *string               `db:"password_reset_code" json:"password_reset_code"`
	PasswordResetExpires     pgtype.Timestamptz    `db:"password_reset_expires" json:"password_reset_expires"`
	PasswordResetAttempts    int32                 `db:"password_reset_attempts" json:"password_reset_attempts"`
}
