// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_updates.sql

package sqlc

import (
	"context"
)

const deleteReleaseChannel = `-- name: DeleteReleaseChannel :execrows
DELETE FROM app_releases WHERE platform = $1 AND channel = $2
`

type DeleteReleaseChannelParams struct {
	Platform string `db:"platform" json:"platform"`
	Channel  string `db:"channel" json:"channel"`
}

// Node deleteChannel(): releaseRepo.delete({ platform, channel }).
func (q *Queries) DeleteReleaseChannel(ctx context.Context, arg DeleteReleaseChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReleaseChannel, arg.Platform, arg.Channel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnabledReleaseByChannel = `-- name: GetEnabledReleaseByChannel :one
SELECT platform, version, download_url, sha256, release_notes, required, updated_at, channel, enabled
FROM app_releases
WHERE platform = $1 AND channel = $2 AND enabled = true
`

type GetEnabledReleaseByChannelParams struct {
	Platform string `db:"platform" json:"platform"`
	Channel  string `db:"channel" json:"channel"`
}

func (q *Queries) GetEnabledReleaseByChannel(ctx context.Context, arg GetEnabledReleaseByChannelParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, getEnabledReleaseByChannel, arg.Platform, arg.Channel)
	var i AppRelease
	err := row.Scan(
		&i.Platform,
		&i.Version,
		&i.DownloadUrl,
		&i.Sha256,
		&i.ReleaseNotes,
		&i.Required,
		&i.UpdatedAt,
		&i.Channel,
		&i.Enabled,
	)
	return i, err
}

const getReleaseChannel = `-- name: GetReleaseChannel :one
SELECT platform, version, download_url, sha256, release_notes, required, updated_at, channel, enabled FROM app_releases WHERE platform = $1 AND channel = $2
`

type GetReleaseChannelParams struct {
	Platform string `db:"platform" json:"platform"`
	Channel  string `db:"channel" json:"channel"`
}

// Node upsertChannel(): releaseRepo.findOne({ where: { platform, channel } }).
func (q *Queries) GetReleaseChannel(ctx context.Context, arg GetReleaseChannelParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, getReleaseChannel, arg.Platform, arg.Channel)
	var i AppRelease
	err := row.Scan(
		&i.Platform,
		&i.Version,
		&i.DownloadUrl,
		&i.Sha256,
		&i.ReleaseNotes,
		&i.Required,
		&i.UpdatedAt,
		&i.Channel,
		&i.Enabled,
	)
	return i, err
}

const getReleasePolicy = `-- name: GetReleasePolicy :one

SELECT platform, preferred, store_status, notes, updated_at
FROM app_release_policies
WHERE platform = $1
`

// internal/shared/pg/queries_updates.sql
func (q *Queries) GetReleasePolicy(ctx context.Context, platform string) (AppReleasePolicy, error) {
	row := q.db.QueryRow(ctx, getReleasePolicy, platform)
	var i AppReleasePolicy
	err := row.Scan(
		&i.Platform,
		&i.Preferred,
		&i.StoreStatus,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReleaseChannel = `-- name: InsertReleaseChannel :one
INSERT INTO app_releases (platform, channel, version, download_url, sha256, release_notes, required, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING platform, version, download_url, sha256, release_notes, required, updated_at, channel, enabled
`

type InsertReleaseChannelParams struct {
	Platform     string `db:"platform" json:"platform"`
	Channel      string `db:"channel" json:"channel"`
	Version      string `db:"version" json:"version"`
	DownloadUrl  string `db:"download_url" json:"download_url"`
	Sha256       string `db:"sha256" json:"sha256"`
	ReleaseNotes string `db:"release_notes" json:"release_notes"`
	Required     bool   `db:"required" json:"required"`
	Enabled      bool   `db:"enabled" json:"enabled"`
}

// Node upsertChannel() create path. The use case supplies merged values.
func (q *Queries) InsertReleaseChannel(ctx context.Context, arg InsertReleaseChannelParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, insertReleaseChannel,
		arg.Platform,
		arg.Channel,
		arg.Version,
		arg.DownloadUrl,
		arg.Sha256,
		arg.ReleaseNotes,
		arg.Required,
		arg.Enabled,
	)
	var i AppRelease
	err := row.Scan(
		&i.Platform,
		&i.Version,
		&i.DownloadUrl,
		&i.Sha256,
		&i.ReleaseNotes,
		&i.Required,
		&i.UpdatedAt,
		&i.Channel,
		&i.Enabled,
	)
	return i, err
}

const insertReleasePolicy = `-- name: InsertReleasePolicy :one
INSERT INTO app_release_policies (platform, preferred, store_status, notes)
VALUES ($1, $2, $3, $4)
RETURNING platform, preferred, store_status, notes, updated_at
`

type InsertReleasePolicyParams struct {
	Platform    string `db:"platform" json:"platform"`
	Preferred   string `db:"preferred" json:"preferred"`
	StoreStatus string `db:"store_status" json:"store_status"`
	Notes       string `db:"notes" json:"notes"`
}

// Node PoliciesService.upsert() create path. The use case supplies merged values.
func (q *Queries) InsertReleasePolicy(ctx context.Context, arg InsertReleasePolicyParams) (AppReleasePolicy, error) {
	row := q.db.QueryRow(ctx, insertReleasePolicy,
		arg.Platform,
		arg.Preferred,
		arg.StoreStatus,
		arg.Notes,
	)
	var i AppReleasePolicy
	err := row.Scan(
		&i.Platform,
		&i.Preferred,
		&i.StoreStatus,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReleasePolicies = `-- name: ListAllReleasePolicies :many
SELECT platform, preferred, store_status, notes, updated_at FROM app_release_policies
`

// Node ReleasesService.listAll(): policyRepo.find() — every policy row.
func (q *Queries) ListAllReleasePolicies(ctx context.Context) ([]AppReleasePolicy, error) {
	rows, err := q.db.Query(ctx, listAllReleasePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppReleasePolicy{}
	for rows.Next() {
		var i AppReleasePolicy
		if err := rows.Scan(
			&i.Platform,
			&i.Preferred,
			&i.StoreStatus,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReleases = `-- name: ListAllReleases :many
SELECT platform, version, download_url, sha256, release_notes, required, updated_at, channel, enabled FROM app_releases
`

// Node ReleasesService.listAll(): releaseRepo.find() — every (platform, channel) row.
func (q *Queries) ListAllReleases(ctx context.Context) ([]AppRelease, error) {
	rows, err := q.db.Query(ctx, listAllReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRelease{}
	for rows.Next() {
		var i AppRelease
		if err := rows.Scan(
			&i.Platform,
			&i.Version,
			&i.DownloadUrl,
			&i.Sha256,
			&i.ReleaseNotes,
			&i.Required,
			&i.UpdatedAt,
			&i.Channel,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReleaseChannel = `-- name: UpdateReleaseChannel :one
UPDATE app_releases
SET version = $3,
    download_url = $4,
    sha256 = $5,
    release_notes = $6,
    required = $7,
    enabled = $8,
    updated_at = now()
WHERE platform = $1 AND channel = $2
RETURNING platform, version, download_url, sha256, release_notes, required, updated_at, channel, enabled
`

type UpdateReleaseChannelParams struct {
	Platform     string `db:"platform" json:"platform"`
	Channel      string `db:"channel" json:"channel"`
	Version      string `db:"version" json:"version"`
	DownloadUrl  string `db:"download_url" json:"download_url"`
	Sha256       string `db:"sha256" json:"sha256"`
	ReleaseNotes string `db:"release_notes" json:"release_notes"`
	Required     bool   `db:"required" json:"required"`
	Enabled      bool   `db:"enabled" json:"enabled"`
}

// Node upsertChannel() update path. The use case supplies merged values.
func (q *Queries) UpdateReleaseChannel(ctx context.Context, arg UpdateReleaseChannelParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, updateReleaseChannel,
		arg.Platform,
		arg.Channel,
		arg.Version,
		arg.DownloadUrl,
		arg.Sha256,
		arg.ReleaseNotes,
		arg.Required,
		arg.Enabled,
	)
	var i AppRelease
	err := row.Scan(
		&i.Platform,
		&i.Version,
		&i.DownloadUrl,
		&i.Sha256,
		&i.ReleaseNotes,
		&i.Required,
		&i.UpdatedAt,
		&i.Channel,
		&i.Enabled,
	)
	return i, err
}

const updateReleasePolicy = `-- name: UpdateReleasePolicy :one
UPDATE app_release_policies
SET preferred = $2,
    store_status = $3,
    notes = $4,
    updated_at = now()
WHERE platform = $1
RETURNING platform, preferred, store_status, notes, updated_at
`

type UpdateReleasePolicyParams struct {
	Platform    string `db:"platform" json:"platform"`
	Preferred   string `db:"preferred" json:"preferred"`
	StoreStatus string `db:"store_status" json:"store_status"`
	Notes       string `db:"notes" json:"notes"`
}

// Node PoliciesService.upsert() update path. The use case supplies merged values.
func (q *Queries) UpdateReleasePolicy(ctx context.Context, arg UpdateReleasePolicyParams) (AppReleasePolicy, error) {
	row := q.db.QueryRow(ctx, updateReleasePolicy,
		arg.Platform,
		arg.Preferred,
		arg.StoreStatus,
		arg.Notes,
	)
	var i AppReleasePolicy
	err := row.Scan(
		&i.Platform,
		&i.Preferred,
		&i.StoreStatus,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}
