// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_aiprovider.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const demoteDefaultAiProviders = `-- name: DemoteDefaultAiProviders :exec
UPDATE ai_providers SET is_default = false WHERE is_default = true
`

func (q *Queries) DemoteDefaultAiProviders(ctx context.Context) error {
	_, err := q.db.Exec(ctx, demoteDefaultAiProviders)
	return err
}

const getAiProviderByID = `-- name: GetAiProviderByID :one
SELECT id, name, type, endpoint_url, api_key, model, temperature::text AS temperature,
       is_default, is_active, created_at, updated_at
FROM ai_providers WHERE id = $1
`

type GetAiProviderByIDRow struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	Name        string              `db:"name" json:"name"`
	Type        AiProvidersTypeEnum `db:"type" json:"type"`
	EndpointUrl string              `db:"endpoint_url" json:"endpoint_url"`
	ApiKey      string              `db:"api_key" json:"api_key"`
	Model       string              `db:"model" json:"model"`
	Temperature string              `db:"temperature" json:"temperature"`
	IsDefault   bool                `db:"is_default" json:"is_default"`
	IsActive    bool                `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamp    `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAiProviderByID(ctx context.Context, id pgtype.UUID) (GetAiProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getAiProviderByID, id)
	var i GetAiProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.EndpointUrl,
		&i.ApiKey,
		&i.Model,
		&i.Temperature,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAiProvider = `-- name: InsertAiProvider :one
INSERT INTO ai_providers (name, type, endpoint_url, api_key, model, temperature, is_default, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, type, endpoint_url, api_key, model, temperature::text AS temperature,
          is_default, is_active, created_at, updated_at
`

type InsertAiProviderParams struct {
	Name        string              `db:"name" json:"name"`
	Type        AiProvidersTypeEnum `db:"type" json:"type"`
	EndpointUrl string              `db:"endpoint_url" json:"endpoint_url"`
	ApiKey      string              `db:"api_key" json:"api_key"`
	Model       string              `db:"model" json:"model"`
	Temperature pgtype.Numeric      `db:"temperature" json:"temperature"`
	IsDefault   bool                `db:"is_default" json:"is_default"`
	IsActive    bool                `db:"is_active" json:"is_active"`
}

type InsertAiProviderRow struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	Name        string              `db:"name" json:"name"`
	Type        AiProvidersTypeEnum `db:"type" json:"type"`
	EndpointUrl string              `db:"endpoint_url" json:"endpoint_url"`
	ApiKey      string              `db:"api_key" json:"api_key"`
	Model       string              `db:"model" json:"model"`
	Temperature string              `db:"temperature" json:"temperature"`
	IsDefault   bool                `db:"is_default" json:"is_default"`
	IsActive    bool                `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamp    `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertAiProvider(ctx context.Context, arg InsertAiProviderParams) (InsertAiProviderRow, error) {
	row := q.db.QueryRow(ctx, insertAiProvider,
		arg.Name,
		arg.Type,
		arg.EndpointUrl,
		arg.ApiKey,
		arg.Model,
		arg.Temperature,
		arg.IsDefault,
		arg.IsActive,
	)
	var i InsertAiProviderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.EndpointUrl,
		&i.ApiKey,
		&i.Model,
		&i.Temperature,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAiProviders = `-- name: ListAiProviders :many

SELECT id, name, type, endpoint_url, api_key, model, temperature::text AS temperature,
       is_default, is_active, created_at, updated_at
FROM ai_providers
ORDER BY created_at ASC
`

type ListAiProvidersRow struct {
	ID          pgtype.UUID         `db:"id" json:"id"`
	Name        string              `db:"name" json:"name"`
	Type        AiProvidersTypeEnum `db:"type" json:"type"`
	EndpointUrl string              `db:"endpoint_url" json:"endpoint_url"`
	ApiKey      string              `db:"api_key" json:"api_key"`
	Model       string              `db:"model" json:"model"`
	Temperature string              `db:"temperature" json:"temperature"`
	IsDefault   bool                `db:"is_default" json:"is_default"`
	IsActive    bool                `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamp    `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp    `db:"updated_at" json:"updated_at"`
}

// AI provider admin CRUD (Phase 4c-2). The temperature column is
// decimal(3,2); the Node entity declares it WITHOUT a numeric transformer,
// so TypeORM returns it as a JS string ("0.30"). To reproduce that exact
// 2-decimal string in Go (and dodge pgtype.Numeric formatting), every read
// casts `temperature::text AS temperature` so sqlc types it as a Go string
// with Postgres-preserved scale-2 text.
func (q *Queries) ListAiProviders(ctx context.Context) ([]ListAiProvidersRow, error) {
	rows, err := q.db.Query(ctx, listAiProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAiProvidersRow{}
	for rows.Next() {
		var i ListAiProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.EndpointUrl,
			&i.ApiKey,
			&i.Model,
			&i.Temperature,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAiProvider = `-- name: SoftDeleteAiProvider :exec
UPDATE ai_providers SET is_default = false, is_active = false WHERE id = $1
`

func (q *Queries) SoftDeleteAiProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAiProvider, id)
	return err
}
