// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Selects the active default AI provider. NestJS picks the same row in
	// AiProvidersService.findActive — keep the ORDER BY in sync there + here
	// (is_default DESC, is_active = TRUE).
	ActiveAIProvider(ctx context.Context) (ActiveAIProviderRow, error)
	// Today's daily-quota tally for the user. Compared against
	// plan.daily_limit in the application layer (so the limit can come
	// from a fallback when the user has no subscription).
	CountTodayUsage(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Mirrors usageService.countTodayByUser: rows since local midnight.
	// The caller passes the midnight boundary so timezone handling matches
	// the Node process (new Date(); setHours(0,0,0,0)).
	CountUsageToday(ctx context.Context, arg CountUsageTodayParams) (int64, error)
	CreateFreeSubscription(ctx context.Context, arg CreateFreeSubscriptionParams) error
	// Insert a pending payment. Defaults (id, created_at, updated_at) are returned.
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Cron pass 2: flip active|cancelled subs past expiry to expired, returning
	// the affected rows so the caller can email each. expires_at left untouched.
	ExpireLapsedSubs(ctx context.Context, expiresAt pgtype.Timestamp) ([]ExpireLapsedSubsRow, error)
	// validate(): resolve a presented token's hash to owner + scopes. Returns id
	// too — Verify (T13) fires TouchTokenLastUsed by id afterwards.
	FindActiveTokenByHash(ctx context.Context, tokenHash string) (FindActiveTokenByHashRow, error)
	FindFreePlan(ctx context.Context) (FindFreePlanRow, error)
	FindUserByAppleId(ctx context.Context, appleID *string) (FindUserByAppleIdRow, error)
	FindUserByFacebookId(ctx context.Context, facebookID *string) (FindUserByFacebookIdRow, error)
	FindUserByGoogleId(ctx context.Context, googleID *string) (FindUserByGoogleIdRow, error)
	FindUserByTiktokId(ctx context.Context, tiktokID *string) (FindUserByTiktokIdRow, error)
	// Queries for the /rewrite microservice's Postgres adapter.
	// sqlc compiles these against schema.sql at build time; mistakes are
	// caught BEFORE the service ever boots (Rule #1 — compile-time over
	// runtime).
	//
	// Each query has three sqlc directives:
	//   :one  → returns exactly one row (errors if zero)
	//   :many → returns a slice of rows
	//   :exec → no rows; returns affected-row count
	//
	// Naming convention: <Verb><Subject>, mirrors Go function names sqlc
	// generates (FindUserWithPlan, IncrementUsageToday, …).
	// Resolves user + their active subscription's plan in one query so the
	// quota check is a single round-trip. LEFT JOIN because users without
	// an active subscription fall back to the free tier (plan_id NULL).
	// Filter on subscriptions.status = 'active' so cancelled subs don't
	// still grant their old plan.
	FindUserWithPlan(ctx context.Context, id pgtype.UUID) (FindUserWithPlanRow, error)
	// GET /subscription: newest active sub + plan fields incl billing_period.
	// Distinct from GetActiveSubscriptionByUserID (which omits billing_period
	// and is pinned for /auth/account).
	GetActiveSubWithPlan(ctx context.Context, userID pgtype.UUID) (GetActiveSubWithPlanRow, error)
	// Mirrors subscriptionsService.findActiveByUserId: newest ACTIVE
	// subscription for the user, joined to its plan. ORDER BY created_at
	// DESC + LIMIT 1 reproduces TypeORM order:{created_at:'DESC'} findOne.
	GetActiveSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetActiveSubscriptionByUserIDRow, error)
	// The single app_settings row's token lifetimes. No row → caller uses
	// defaults (15 / 90), matching Node's `?? 15` / `?? 90`.
	GetAuthTokenSettings(ctx context.Context) (GetAuthTokenSettingsRow, error)
	// Phase 1a auth queries. Read the live NestJS-owned schema as-is.
	// Full projection for /auth/login. password_hash is nullable
	// (social-only accounts have none). No email normalization — Node's
	// login passes the email through unchanged.
	GetAuthUserByEmail(ctx context.Context, email string) (GetAuthUserByEmailRow, error)
	// Same projection keyed by id — used by refresh, change-password, account.
	GetAuthUserByID(ctx context.Context, id pgtype.UUID) (GetAuthUserByIDRow, error)
	// The single app_settings row's client_log_level, surfaced by
	// GET /health. There is exactly one settings row (Node does
	// `findOne({ where: {} })`); LIMIT 1 matches that.
	GetClientLogLevel(ctx context.Context) (string, error)
	// app_settings creds: both columns are NOT NULL (default '').
	GetEmailSettings(ctx context.Context) (GetEmailSettingsRow, error)
	// DB template override. PK column is template_key (not key).
	GetEmailTemplateByKey(ctx context.Context, templateKey string) (GetEmailTemplateByKeyRow, error)
	// updated_at of the user's most-recently expired subscription (free-tier
	// just_expired banner). No row → caller treats as nil.
	GetLastExpiredAt(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamp, error)
	// internal/shared/pg/queries_payment.sql
	// Payment persistence (read paths for Phase 3a). Table public.payments is
	// owned by the live NestJS-managed schema; mirror PaymentService read
	// semantics exactly. Timestamps are "without time zone".
	// getStatus(referenceCode): the pending/settled payment plus the plan name the
	// controller surfaces as plan_name. LEFT JOIN so a payment whose plan row was
	// deleted still returns (plan_name NULL), matching TypeORM relations:['plan']
	// with a possibly-null relation.
	GetPaymentByReference(ctx context.Context, referenceCode string) (GetPaymentByReferenceRow, error)
	// Checkout-time provider credentials from the singleton app_settings row.
	// All columns are NOT NULL DEFAULT ''. No row → pgx.ErrNoRows (caller treats
	// as all-empty → env fallback per resolveCredential).
	GetPaymentCredentials(ctx context.Context) (GetPaymentCredentialsRow, error)
	// payment_methods_enabled CSV from the singleton app_settings row. NOT NULL
	// (default ''); empty string means unconfigured → caller falls back to env
	// then default. No row at all → pgx.ErrNoRows, mapped to found=false.
	GetPaymentMethodsEnabled(ctx context.Context) (string, error)
	// Plan fields createCheckout needs (price_cents drives the free-plan guard +
	// payment.amount; the rest feed the strategy). No row → pgx.ErrNoRows.
	GetPlanForCheckout(ctx context.Context, id pgtype.UUID) (GetPlanForCheckoutRow, error)
	GetUserAuthState(ctx context.Context, email string) (GetUserAuthStateRow, error)
	// Phase 0 core-endpoint queries (health + /auth/me). Kept separate
	// from the rewrite module's queries.sql so the core package depends on
	// the shared sqlc types only, never on a feature module.
	// Minimal user projection for GET /auth/me — id, email, role. Mirrors
	// the fields Node's /auth/me returns from the JWT-resolved user.
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// User fields createCheckout / portal / cancel need. No row → pgx.ErrNoRows.
	GetUserForCheckout(ctx context.Context, id pgtype.UUID) (GetUserForCheckoutRow, error)
	// Audit row for every deliver attempt (suppressed/skipped/sent/failed).
	InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) error
	// mint() insert. Returns the projection list() serializes (token_hash and
	// user_id stripped by the controller, so omitted here).
	InsertExtensionToken(ctx context.Context, arg InsertExtensionTokenParams) (InsertExtensionTokenRow, error)
	// Records one /rewrite call for daily quota tracking + analytics.
	// Mirrors NestJS UsageService.log: same columns, same names, same
	// precision so the two backends populate identical rows.
	InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) error
	// Lowercased-email suppression check (bounce/complaint list).
	IsEmailSuppressed(ctx context.Context, email string) (bool, error)
	LinkSocialApple(ctx context.Context, arg LinkSocialAppleParams) error
	LinkSocialFacebook(ctx context.Context, arg LinkSocialFacebookParams) error
	LinkSocialGoogle(ctx context.Context, arg LinkSocialGoogleParams) error
	LinkSocialTiktok(ctx context.Context, arg LinkSocialTiktokParams) error
	// Mirrors plansService.findAll(): every active plan, cheapest first.
	// No tiebreaker beyond price_cents (matches TypeORM order:{price_cents:'ASC'}).
	ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error)
	// list(): active tokens for the user, newest first
	// (TypeORM where:{user_id, revoked_at:IsNull()} order:{created_at:'DESC'}).
	ListActiveTokens(ctx context.Context, userID pgtype.UUID) ([]ListActiveTokensRow, error)
	// findByUser(userId): the user's 20 most-recent payments, newest first, each
	// with its plan (TypeORM relations:['plan'] order:{created_at:'DESC'} take:20).
	ListPaymentsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPaymentsByUserRow, error)
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error
	ResetPasswordHash(ctx context.Context, arg ResetPasswordHashParams) error
	// Extension-token persistence (dr_ext_* keyboard/share tokens).
	// Read the live NestJS-owned schema as-is; mirror ExtensionTokenService
	// (backend/src/auth/extension-token.service.ts) WHERE semantics exactly.
	// Table: public.extension_tokens — scopes text[], device_id uuid,
	// timestamps "without time zone".
	// mint() rotates: revoke any still-active token for this (user, device)
	// first so the partial unique index idx_ext_tokens_user_device_active
	// (user_id, device_id) WHERE revoked_at IS NULL doesn't collide.
	RevokeActiveTokensForDevice(ctx context.Context, arg RevokeActiveTokensForDeviceParams) error
	// revoke(): owner-scoped UPDATE keyed by (id, user_id). Node does NOT filter
	// revoked_at IS NULL here, so re-revoking an already-revoked row is a no-op
	// touch of revoked_at — idempotent, controller returns 204 either way.
	RevokeTokenByID(ctx context.Context, arg RevokeTokenByIDParams) error
	SetEmailVerificationCode(ctx context.Context, arg SetEmailVerificationCodeParams) error
	SetPasswordResetAttempts(ctx context.Context, arg SetPasswordResetAttemptsParams) error
	SetPasswordResetCode(ctx context.Context, arg SetPasswordResetCodeParams) error
	// Cron pass 1: active subs whose expiry falls in the reminder window.
	// Bounds passed by caller (now+2.5d, now+3.5d) to keep tz in the Go process.
	SubsDueForRenewal(ctx context.Context, arg SubsDueForRenewalParams) ([]SubsDueForRenewalRow, error)
	// validate() write-behind: bump last_used_at. Failures non-fatal (caller
	// ignores the error so the request still succeeds).
	TouchTokenLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdatePaymentQRData(ctx context.Context, arg UpdatePaymentQRDataParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) error
}

var _ Querier = (*Queries)(nil)
