// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_errors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountErrors = `-- name: AdminCountErrors :one
SELECT COUNT(*) FROM error_reports
WHERE ($1::text IS NULL OR platform = $1)
  AND ($2::int IS NULL OR status = $2)
  AND ($3::text IS NULL OR severity = $3)
`

type AdminCountErrorsParams struct {
	Platform *string `db:"platform" json:"platform"`
	Status   *int32  `db:"status" json:"status"`
	Severity *string `db:"severity" json:"severity"`
}

func (q *Queries) AdminCountErrors(ctx context.Context, arg AdminCountErrorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountErrors, arg.Platform, arg.Status, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDeleteError = `-- name: AdminDeleteError :execrows
DELETE FROM error_reports WHERE id = $1
`

func (q *Queries) AdminDeleteError(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteError, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminErrorFixCandidates = `-- name: AdminErrorFixCandidates :many
SELECT id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no FROM error_reports
WHERE status = 0 AND ai_fix_proposal IS NULL AND count >= 2
ORDER BY count DESC, last_seen_at DESC
LIMIT $1
`

// Cron: status=0 AND ai_fix_proposal IS NULL AND count >= 2,
// ORDER BY count DESC, last_seen_at DESC, LIMIT 10.
func (q *Queries) AdminErrorFixCandidates(ctx context.Context, limit int32) ([]ErrorReport, error) {
	rows, err := q.db.Query(ctx, adminErrorFixCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorReport{}
	for rows.Next() {
		var i ErrorReport
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.AppVersion,
			&i.Severity,
			&i.ErrorType,
			&i.Message,
			&i.StackTrace,
			&i.Context,
			&i.UserID,
			&i.DeviceID,
			&i.Fingerprint,
			&i.Count,
			&i.Status,
			&i.AiFixProposal,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.DisplayNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetError = `-- name: AdminGetError :one
SELECT id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no FROM error_reports WHERE id = $1
`

func (q *Queries) AdminGetError(ctx context.Context, id pgtype.UUID) (ErrorReport, error) {
	row := q.db.QueryRow(ctx, adminGetError, id)
	var i ErrorReport
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AppVersion,
		&i.Severity,
		&i.ErrorType,
		&i.Message,
		&i.StackTrace,
		&i.Context,
		&i.UserID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.Count,
		&i.Status,
		&i.AiFixProposal,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DisplayNo,
	)
	return i, err
}

const adminListErrors = `-- name: AdminListErrors :many
SELECT id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no FROM error_reports
WHERE ($3::text IS NULL OR platform = $3)
  AND ($4::int IS NULL OR status = $4)
  AND ($5::text IS NULL OR severity = $5)
ORDER BY last_seen_at DESC
LIMIT $1 OFFSET $2
`

type AdminListErrorsParams struct {
	Limit    int32   `db:"limit" json:"limit"`
	Offset   int32   `db:"offset" json:"offset"`
	Platform *string `db:"platform" json:"platform"`
	Status   *int32  `db:"status" json:"status"`
	Severity *string `db:"severity" json:"severity"`
}

// Node ErrorsService.list(): optional platform/status/severity filters,
// ORDER BY last_seen_at DESC, LIMIT/OFFSET. NULL filter param = no filter.
func (q *Queries) AdminListErrors(ctx context.Context, arg AdminListErrorsParams) ([]ErrorReport, error) {
	rows, err := q.db.Query(ctx, adminListErrors,
		arg.Limit,
		arg.Offset,
		arg.Platform,
		arg.Status,
		arg.Severity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorReport{}
	for rows.Next() {
		var i ErrorReport
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.AppVersion,
			&i.Severity,
			&i.ErrorType,
			&i.Message,
			&i.StackTrace,
			&i.Context,
			&i.UserID,
			&i.DeviceID,
			&i.Fingerprint,
			&i.Count,
			&i.Status,
			&i.AiFixProposal,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.DisplayNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetErrorFixProposal = `-- name: AdminSetErrorFixProposal :one
UPDATE error_reports
SET ai_fix_proposal = $2, status = $3, last_seen_at = now()
WHERE id = $1
RETURNING id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no
`

type AdminSetErrorFixProposalParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	AiFixProposal *string     `db:"ai_fix_proposal" json:"ai_fix_proposal"`
	Status        int32       `db:"status" json:"status"`
}

func (q *Queries) AdminSetErrorFixProposal(ctx context.Context, arg AdminSetErrorFixProposalParams) (ErrorReport, error) {
	row := q.db.QueryRow(ctx, adminSetErrorFixProposal, arg.ID, arg.AiFixProposal, arg.Status)
	var i ErrorReport
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AppVersion,
		&i.Severity,
		&i.ErrorType,
		&i.Message,
		&i.StackTrace,
		&i.Context,
		&i.UserID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.Count,
		&i.Status,
		&i.AiFixProposal,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DisplayNo,
	)
	return i, err
}

const adminSetErrorStatus = `-- name: AdminSetErrorStatus :one
UPDATE error_reports
SET status = $1,
    resolved_at = CASE WHEN $2::boolean THEN $3 ELSE resolved_at END,
    resolved_by = CASE WHEN $2::boolean THEN $4 ELSE resolved_by END,
    last_seen_at = now()
WHERE id = $5
RETURNING id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no
`

type AdminSetErrorStatusParams struct {
	Status      int32              `db:"status" json:"status"`
	SetResolved bool               `db:"set_resolved" json:"set_resolved"`
	ResolvedAt  pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ResolvedBy  *string            `db:"resolved_by" json:"resolved_by"`
	ID          pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) AdminSetErrorStatus(ctx context.Context, arg AdminSetErrorStatusParams) (ErrorReport, error) {
	row := q.db.QueryRow(ctx, adminSetErrorStatus,
		arg.Status,
		arg.SetResolved,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.ID,
	)
	var i ErrorReport
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AppVersion,
		&i.Severity,
		&i.ErrorType,
		&i.Message,
		&i.StackTrace,
		&i.Context,
		&i.UserID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.Count,
		&i.Status,
		&i.AiFixProposal,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DisplayNo,
	)
	return i, err
}

const bumpErrorReport = `-- name: BumpErrorReport :one
UPDATE error_reports SET
  count = count + 1,
  last_seen_at = now(),
  app_version = COALESCE($2, app_version),
  user_id = COALESCE($3, user_id),
  device_id = COALESCE($4, device_id),
  context = COALESCE($5, context)
WHERE fingerprint = $1
RETURNING id, display_no, count, first_seen_at
`

type BumpErrorReportParams struct {
	Fingerprint string      `db:"fingerprint" json:"fingerprint"`
	AppVersion  *string     `db:"app_version" json:"app_version"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID    *string     `db:"device_id" json:"device_id"`
	Context     []byte      `db:"context" json:"context"`
}

type BumpErrorReportRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	DisplayNo   int64              `db:"display_no" json:"display_no"`
	Count       int32              `db:"count" json:"count"`
	FirstSeenAt pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
}

func (q *Queries) BumpErrorReport(ctx context.Context, arg BumpErrorReportParams) (BumpErrorReportRow, error) {
	row := q.db.QueryRow(ctx, bumpErrorReport,
		arg.Fingerprint,
		arg.AppVersion,
		arg.UserID,
		arg.DeviceID,
		arg.Context,
	)
	var i BumpErrorReportRow
	err := row.Scan(
		&i.ID,
		&i.DisplayNo,
		&i.Count,
		&i.FirstSeenAt,
	)
	return i, err
}

const findErrorByFingerprint = `-- name: FindErrorByFingerprint :one

SELECT id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no FROM error_reports WHERE fingerprint = $1
`

// internal/shared/pg/queries_errors.sql
// Crash-report ingest: read-then-write dedup (no ON CONFLICT, matching Node).
func (q *Queries) FindErrorByFingerprint(ctx context.Context, fingerprint string) (ErrorReport, error) {
	row := q.db.QueryRow(ctx, findErrorByFingerprint, fingerprint)
	var i ErrorReport
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AppVersion,
		&i.Severity,
		&i.ErrorType,
		&i.Message,
		&i.StackTrace,
		&i.Context,
		&i.UserID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.Count,
		&i.Status,
		&i.AiFixProposal,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DisplayNo,
	)
	return i, err
}

const insertErrorReport = `-- name: InsertErrorReport :one
INSERT INTO error_reports
  (platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1,0)
RETURNING id, display_no, count, first_seen_at
`

type InsertErrorReportParams struct {
	Platform    string      `db:"platform" json:"platform"`
	AppVersion  *string     `db:"app_version" json:"app_version"`
	Severity    string      `db:"severity" json:"severity"`
	ErrorType   *string     `db:"error_type" json:"error_type"`
	Message     *string     `db:"message" json:"message"`
	StackTrace  *string     `db:"stack_trace" json:"stack_trace"`
	Context     []byte      `db:"context" json:"context"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID    *string     `db:"device_id" json:"device_id"`
	Fingerprint string      `db:"fingerprint" json:"fingerprint"`
}

type InsertErrorReportRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	DisplayNo   int64              `db:"display_no" json:"display_no"`
	Count       int32              `db:"count" json:"count"`
	FirstSeenAt pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
}

func (q *Queries) InsertErrorReport(ctx context.Context, arg InsertErrorReportParams) (InsertErrorReportRow, error) {
	row := q.db.QueryRow(ctx, insertErrorReport,
		arg.Platform,
		arg.AppVersion,
		arg.Severity,
		arg.ErrorType,
		arg.Message,
		arg.StackTrace,
		arg.Context,
		arg.UserID,
		arg.DeviceID,
		arg.Fingerprint,
	)
	var i InsertErrorReportRow
	err := row.Scan(
		&i.ID,
		&i.DisplayNo,
		&i.Count,
		&i.FirstSeenAt,
	)
	return i, err
}
