// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_users_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSubFullByUser = `-- name: GetActiveSubFullByUser :one
SELECT s.id, s.user_id, s.plan_id, s.status::text AS status, s.store_type::text AS store_type,
       s.store_transaction_id, s.started_at, s.expires_at, s.created_at, s.updated_at,
       p.id AS plan_id_full, p.name AS plan_name, p.daily_limit AS plan_daily_limit,
       p.price_cents AS plan_price_cents, p.currency AS plan_currency,
       p.stripe_price_id AS plan_stripe_price_id, p.trial_days AS plan_trial_days,
       p.billing_period::text AS plan_billing_period, p.is_active AS plan_is_active,
       p.created_at AS plan_created_at, p.updated_at AS plan_updated_at
FROM subscriptions s JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1 AND s.status = 'active'::subscriptions_status_enum
ORDER BY s.created_at DESC LIMIT 1
`

type GetActiveSubFullByUserRow struct {
	ID                 pgtype.UUID      `db:"id" json:"id"`
	UserID             pgtype.UUID      `db:"user_id" json:"user_id"`
	PlanID             pgtype.UUID      `db:"plan_id" json:"plan_id"`
	Status             string           `db:"status" json:"status"`
	StoreType          string           `db:"store_type" json:"store_type"`
	StoreTransactionID *string          `db:"store_transaction_id" json:"store_transaction_id"`
	StartedAt          pgtype.Timestamp `db:"started_at" json:"started_at"`
	ExpiresAt          pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt          pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	PlanIDFull         pgtype.UUID      `db:"plan_id_full" json:"plan_id_full"`
	PlanName           string           `db:"plan_name" json:"plan_name"`
	PlanDailyLimit     int32            `db:"plan_daily_limit" json:"plan_daily_limit"`
	PlanPriceCents     int32            `db:"plan_price_cents" json:"plan_price_cents"`
	PlanCurrency       *string          `db:"plan_currency" json:"plan_currency"`
	PlanStripePriceID  *string          `db:"plan_stripe_price_id" json:"plan_stripe_price_id"`
	PlanTrialDays      int32            `db:"plan_trial_days" json:"plan_trial_days"`
	PlanBillingPeriod  string           `db:"plan_billing_period" json:"plan_billing_period"`
	PlanIsActive       bool             `db:"plan_is_active" json:"plan_is_active"`
	PlanCreatedAt      pgtype.Timestamp `db:"plan_created_at" json:"plan_created_at"`
	PlanUpdatedAt      pgtype.Timestamp `db:"plan_updated_at" json:"plan_updated_at"`
}

// GetActiveSubFullByUser backs GET /admin/users/:id's subscription field
// (subscriptionsService.findActiveByUserId: status ACTIVE, relations ['plan'],
// created_at DESC, take 1). The `user` relation is NOT loaded → omitted from the
// serialised subscription. Enum columns cast ::text so sqlc scans plain Go
// strings (mirrors the temperature::text / billing_period::text pattern). The
// joined plan columns are aliased plan_* to feed the nested plans.PlanEntity.
func (q *Queries) GetActiveSubFullByUser(ctx context.Context, userID pgtype.UUID) (GetActiveSubFullByUserRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubFullByUser, userID)
	var i GetActiveSubFullByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StoreType,
		&i.StoreTransactionID,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanIDFull,
		&i.PlanName,
		&i.PlanDailyLimit,
		&i.PlanPriceCents,
		&i.PlanCurrency,
		&i.PlanStripePriceID,
		&i.PlanTrialDays,
		&i.PlanBillingPeriod,
		&i.PlanIsActive,
		&i.PlanCreatedAt,
		&i.PlanUpdatedAt,
	)
	return i, err
}

const getUserFull = `-- name: GetUserFull :one

SELECT id, email, password_hash, name, is_active, role, auth_provider,
       google_id, facebook_id, tiktok_id, apple_id, avatar_url,
       stripe_customer_id, email_verified, email_verification_code,
       email_verification_expires, password_reset_code, password_reset_expires,
       password_reset_attempts, lemonsqueezy_customer_id, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserFullRow struct {
	ID                       pgtype.UUID           `db:"id" json:"id"`
	Email                    string                `db:"email" json:"email"`
	PasswordHash             *string               `db:"password_hash" json:"password_hash"`
	Name                     string                `db:"name" json:"name"`
	IsActive                 bool                  `db:"is_active" json:"is_active"`
	Role                     UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider             UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	GoogleID                 *string               `db:"google_id" json:"google_id"`
	FacebookID               *string               `db:"facebook_id" json:"facebook_id"`
	TiktokID                 *string               `db:"tiktok_id" json:"tiktok_id"`
	AppleID                  *string               `db:"apple_id" json:"apple_id"`
	AvatarUrl                *string               `db:"avatar_url" json:"avatar_url"`
	StripeCustomerID         *string               `db:"stripe_customer_id" json:"stripe_customer_id"`
	EmailVerified            bool                  `db:"email_verified" json:"email_verified"`
	EmailVerificationCode    *string               `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz    `db:"email_verification_expires" json:"email_verification_expires"`
	PasswordResetCode        *string               `db:"password_reset_code" json:"password_reset_code"`
	PasswordResetExpires     pgtype.Timestamptz    `db:"password_reset_expires" json:"password_reset_expires"`
	PasswordResetAttempts    int32                 `db:"password_reset_attempts" json:"password_reset_attempts"`
	LemonsqueezyCustomerID   *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	CreatedAt                pgtype.Timestamp      `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamp      `db:"updated_at" json:"updated_at"`
}

// Admin user CRUD (Phase 4c-2). GET /admin/users/:id returns the FULL
// TypeORM User entity (the `user` field); PATCH /admin/users/:id re-reads
// it. Only the full-row GET is static — the bespoke paginated list, its
// COUNT, and the partial UPDATE have runtime WHERE/ORDER/SET and so are
// assembled in Go on the pool (NOT here). Columns are listed in
// entity-declaration order (src/users/entities/user.entity.ts) so the
// scan lines up with user.UserDetail. The two nullable timestamps are
// timestamptz; the two non-null timestamps are timestamp.
func (q *Queries) GetUserFull(ctx context.Context, id pgtype.UUID) (GetUserFullRow, error) {
	row := q.db.QueryRow(ctx, getUserFull, id)
	var i GetUserFullRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleID,
		&i.FacebookID,
		&i.TiktokID,
		&i.AppleID,
		&i.AvatarUrl,
		&i.StripeCustomerID,
		&i.EmailVerified,
		&i.EmailVerificationCode,
		&i.EmailVerificationExpires,
		&i.PasswordResetCode,
		&i.PasswordResetExpires,
		&i.PasswordResetAttempts,
		&i.LemonsqueezyCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recentUsageByUser = `-- name: RecentUsageByUser :many
SELECT id, user_id, tone, input_length, output_length, ai_provider_id, response_time_ms, created_at
FROM usage_logs WHERE user_id = $1 ORDER BY created_at DESC LIMIT 20
`

// RecentUsageByUser backs GET /admin/users/:id's recent_usage field
// (usageService.findRecentByUser, default limit 20, created_at DESC). Relations
// (user, ai_provider) are NOT loaded by Node, so only the column fields select.
func (q *Queries) RecentUsageByUser(ctx context.Context, userID pgtype.UUID) ([]UsageLog, error) {
	rows, err := q.db.Query(ctx, recentUsageByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageLog{}
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tone,
			&i.InputLength,
			&i.OutputLength,
			&i.AiProviderID,
			&i.ResponseTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
