// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_emailtemplates.sql

package sqlc

import (
	"context"
)

const listEmailTemplates = `-- name: ListEmailTemplates :many
SELECT template_key, subject, html FROM email_templates
`

type ListEmailTemplatesRow struct {
	TemplateKey string `db:"template_key" json:"template_key"`
	Subject     string `db:"subject" json:"subject"`
	Html        string `db:"html" json:"html"`
}

func (q *Queries) ListEmailTemplates(ctx context.Context) ([]ListEmailTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listEmailTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailTemplatesRow{}
	for rows.Next() {
		var i ListEmailTemplatesRow
		if err := rows.Scan(&i.TemplateKey, &i.Subject, &i.Html); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
