// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_adminauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAdminByEmailLower = `-- name: FindAdminByEmailLower :one

SELECT id, email, password_hash, name, is_active, role, created_at, updated_at FROM admin_users WHERE LOWER(email) = LOWER($1)
`

// internal/shared/pg/queries_adminauth.sql
// Admin authentication (POST /admin/auth/login, change-password, GET me).
// admin_users is the portal-admin table, separate from `users` (customers).
func (q *Queries) FindAdminByEmailLower(ctx context.Context, lower string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByEmailLower, lower)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAdminByID = `-- name: FindAdminByID :one
SELECT id, email, password_hash, name, is_active, role, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) FindAdminByID(ctx context.Context, id pgtype.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, findAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminPasswordHash = `-- name: UpdateAdminPasswordHash :exec
UPDATE admin_users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateAdminPasswordHashParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateAdminPasswordHash(ctx context.Context, arg UpdateAdminPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAdminPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
