// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_bugreports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBugReport = `-- name: InsertBugReport :one
INSERT INTO bug_reports
  (source, description, screenshot_path, screenshot_filename, app_version,
   os_info, user_id, user_email, context, status, kind)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'new','bug')
RETURNING id, display_no
`

type InsertBugReportParams struct {
	Source             string      `db:"source" json:"source"`
	Description        string      `db:"description" json:"description"`
	ScreenshotPath     *string     `db:"screenshot_path" json:"screenshot_path"`
	ScreenshotFilename *string     `db:"screenshot_filename" json:"screenshot_filename"`
	AppVersion         *string     `db:"app_version" json:"app_version"`
	OsInfo             *string     `db:"os_info" json:"os_info"`
	UserID             pgtype.UUID `db:"user_id" json:"user_id"`
	UserEmail          *string     `db:"user_email" json:"user_email"`
	Context            []byte      `db:"context" json:"context"`
}

type InsertBugReportRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	DisplayNo int64       `db:"display_no" json:"display_no"`
}

func (q *Queries) InsertBugReport(ctx context.Context, arg InsertBugReportParams) (InsertBugReportRow, error) {
	row := q.db.QueryRow(ctx, insertBugReport,
		arg.Source,
		arg.Description,
		arg.ScreenshotPath,
		arg.ScreenshotFilename,
		arg.AppVersion,
		arg.OsInfo,
		arg.UserID,
		arg.UserEmail,
		arg.Context,
	)
	var i InsertBugReportRow
	err := row.Scan(&i.ID, &i.DisplayNo)
	return i, err
}

const userExists = `-- name: UserExists :one

SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

// internal/shared/pg/queries_bugreports.sql
// Public bug-report ingest (POST /bug-reports, multipart with optional
// screenshot). user_id is nulled when the JWT outlives its user.
func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
