// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByReference = `-- name: GetPaymentByReference :one

SELECT
  p.id, p.user_id, p.plan_id, p.amount, p.currency, p.method, p.status,
  p.provider_ref, p.reference_code, p.qr_data, p.notes,
  p.expires_at, p.completed_at, p.created_at, p.updated_at,
  pl.name AS plan_name
FROM payments p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.reference_code = $1
LIMIT 1
`

type GetPaymentByReferenceRow struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	UserID        pgtype.UUID      `db:"user_id" json:"user_id"`
	PlanID        pgtype.UUID      `db:"plan_id" json:"plan_id"`
	Amount        int32            `db:"amount" json:"amount"`
	Currency      string           `db:"currency" json:"currency"`
	Method        string           `db:"method" json:"method"`
	Status        string           `db:"status" json:"status"`
	ProviderRef   *string          `db:"provider_ref" json:"provider_ref"`
	ReferenceCode string           `db:"reference_code" json:"reference_code"`
	QrData        *string          `db:"qr_data" json:"qr_data"`
	Notes         *string          `db:"notes" json:"notes"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CompletedAt   pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	PlanName      *string          `db:"plan_name" json:"plan_name"`
}

// internal/shared/pg/queries_payment.sql
// Payment persistence (read paths for Phase 3a). Table public.payments is
// owned by the live NestJS-managed schema; mirror PaymentService read
// semantics exactly. Timestamps are "without time zone".
// getStatus(referenceCode): the pending/settled payment plus the plan name the
// controller surfaces as plan_name. LEFT JOIN so a payment whose plan row was
// deleted still returns (plan_name NULL), matching TypeORM relations:['plan']
// with a possibly-null relation.
func (q *Queries) GetPaymentByReference(ctx context.Context, referenceCode string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, referenceCode)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.ProviderRef,
		&i.ReferenceCode,
		&i.QrData,
		&i.Notes,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
	)
	return i, err
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT
  p.id, p.user_id, p.plan_id, p.amount, p.currency, p.method, p.status,
  p.provider_ref, p.reference_code, p.qr_data, p.notes,
  p.expires_at, p.completed_at, p.created_at, p.updated_at,
  pl.id AS plan_pk, pl.name AS plan_name, pl.daily_limit AS plan_daily_limit,
  pl.price_cents AS plan_price_cents, pl.currency AS plan_currency,
  pl.stripe_price_id AS plan_stripe_price_id, pl.trial_days AS plan_trial_days,
  pl.billing_period AS plan_billing_period, pl.is_active AS plan_is_active,
  pl.created_at AS plan_created_at, pl.updated_at AS plan_updated_at
FROM payments p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.user_id = $1
ORDER BY p.created_at DESC
LIMIT 20
`

type ListPaymentsByUserRow struct {
	ID                pgtype.UUID             `db:"id" json:"id"`
	UserID            pgtype.UUID             `db:"user_id" json:"user_id"`
	PlanID            pgtype.UUID             `db:"plan_id" json:"plan_id"`
	Amount            int32                   `db:"amount" json:"amount"`
	Currency          string                  `db:"currency" json:"currency"`
	Method            string                  `db:"method" json:"method"`
	Status            string                  `db:"status" json:"status"`
	ProviderRef       *string                 `db:"provider_ref" json:"provider_ref"`
	ReferenceCode     string                  `db:"reference_code" json:"reference_code"`
	QrData            *string                 `db:"qr_data" json:"qr_data"`
	Notes             *string                 `db:"notes" json:"notes"`
	ExpiresAt         pgtype.Timestamp        `db:"expires_at" json:"expires_at"`
	CompletedAt       pgtype.Timestamp        `db:"completed_at" json:"completed_at"`
	CreatedAt         pgtype.Timestamp        `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp        `db:"updated_at" json:"updated_at"`
	PlanPk            pgtype.UUID             `db:"plan_pk" json:"plan_pk"`
	PlanName          *string                 `db:"plan_name" json:"plan_name"`
	PlanDailyLimit    *int32                  `db:"plan_daily_limit" json:"plan_daily_limit"`
	PlanPriceCents    *int32                  `db:"plan_price_cents" json:"plan_price_cents"`
	PlanCurrency      *string                 `db:"plan_currency" json:"plan_currency"`
	PlanStripePriceID *string                 `db:"plan_stripe_price_id" json:"plan_stripe_price_id"`
	PlanTrialDays     *int32                  `db:"plan_trial_days" json:"plan_trial_days"`
	PlanBillingPeriod *PlansBillingPeriodEnum `db:"plan_billing_period" json:"plan_billing_period"`
	PlanIsActive      *bool                   `db:"plan_is_active" json:"plan_is_active"`
	PlanCreatedAt     pgtype.Timestamp        `db:"plan_created_at" json:"plan_created_at"`
	PlanUpdatedAt     pgtype.Timestamp        `db:"plan_updated_at" json:"plan_updated_at"`
}

// findByUser(userId): the user's 20 most-recent payments, newest first, each
// with its plan (TypeORM relations:['plan'] order:{created_at:'DESC'} take:20).
func (q *Queries) ListPaymentsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPaymentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByUserRow{}
	for rows.Next() {
		var i ListPaymentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.Status,
			&i.ProviderRef,
			&i.ReferenceCode,
			&i.QrData,
			&i.Notes,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanPk,
			&i.PlanName,
			&i.PlanDailyLimit,
			&i.PlanPriceCents,
			&i.PlanCurrency,
			&i.PlanStripePriceID,
			&i.PlanTrialDays,
			&i.PlanBillingPeriod,
			&i.PlanIsActive,
			&i.PlanCreatedAt,
			&i.PlanUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
