// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_updates.sql

package sqlc

import (
	"context"
)

const getEnabledReleaseByChannel = `-- name: GetEnabledReleaseByChannel :one
SELECT platform, version, download_url, sha256, release_notes, required, updated_at, channel, enabled
FROM app_releases
WHERE platform = $1 AND channel = $2 AND enabled = true
`

type GetEnabledReleaseByChannelParams struct {
	Platform string `db:"platform" json:"platform"`
	Channel  string `db:"channel" json:"channel"`
}

func (q *Queries) GetEnabledReleaseByChannel(ctx context.Context, arg GetEnabledReleaseByChannelParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, getEnabledReleaseByChannel, arg.Platform, arg.Channel)
	var i AppRelease
	err := row.Scan(
		&i.Platform,
		&i.Version,
		&i.DownloadUrl,
		&i.Sha256,
		&i.ReleaseNotes,
		&i.Required,
		&i.UpdatedAt,
		&i.Channel,
		&i.Enabled,
	)
	return i, err
}

const getReleasePolicy = `-- name: GetReleasePolicy :one

SELECT platform, preferred, store_status, notes, updated_at
FROM app_release_policies
WHERE platform = $1
`

// internal/shared/pg/queries_updates.sql
func (q *Queries) GetReleasePolicy(ctx context.Context, platform string) (AppReleasePolicy, error) {
	row := q.db.QueryRow(ctx, getReleasePolicy, platform)
	var i AppReleasePolicy
	err := row.Scan(
		&i.Platform,
		&i.Preferred,
		&i.StoreStatus,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}
