// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_plans_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPlan = `-- name: InsertPlan :one
INSERT INTO plans (name, daily_limit, price_cents, billing_period, currency, trial_days, stripe_price_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, name, daily_limit, price_cents, currency, stripe_price_id,
          trial_days, billing_period, is_active, created_at, updated_at
`

type InsertPlanParams struct {
	Name          string                 `db:"name" json:"name"`
	DailyLimit    int32                  `db:"daily_limit" json:"daily_limit"`
	PriceCents    int32                  `db:"price_cents" json:"price_cents"`
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	Currency      *string                `db:"currency" json:"currency"`
	TrialDays     int32                  `db:"trial_days" json:"trial_days"`
	StripePriceID *string                `db:"stripe_price_id" json:"stripe_price_id"`
}

type InsertPlanRow struct {
	ID            pgtype.UUID            `db:"id" json:"id"`
	Name          string                 `db:"name" json:"name"`
	DailyLimit    int32                  `db:"daily_limit" json:"daily_limit"`
	PriceCents    int32                  `db:"price_cents" json:"price_cents"`
	Currency      *string                `db:"currency" json:"currency"`
	StripePriceID *string                `db:"stripe_price_id" json:"stripe_price_id"`
	TrialDays     int32                  `db:"trial_days" json:"trial_days"`
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	IsActive      bool                   `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (InsertPlanRow, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.Name,
		arg.DailyLimit,
		arg.PriceCents,
		arg.BillingPeriod,
		arg.Currency,
		arg.TrialDays,
		arg.StripePriceID,
	)
	var i InsertPlanRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DailyLimit,
		&i.PriceCents,
		&i.Currency,
		&i.StripePriceID,
		&i.TrialDays,
		&i.BillingPeriod,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPlans = `-- name: ListAllPlans :many

SELECT id, name, daily_limit, price_cents, currency, stripe_price_id,
       trial_days, billing_period, is_active, created_at, updated_at
FROM plans ORDER BY created_at ASC
`

type ListAllPlansRow struct {
	ID            pgtype.UUID            `db:"id" json:"id"`
	Name          string                 `db:"name" json:"name"`
	DailyLimit    int32                  `db:"daily_limit" json:"daily_limit"`
	PriceCents    int32                  `db:"price_cents" json:"price_cents"`
	Currency      *string                `db:"currency" json:"currency"`
	StripePriceID *string                `db:"stripe_price_id" json:"stripe_price_id"`
	TrialDays     int32                  `db:"trial_days" json:"trial_days"`
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	IsActive      bool                   `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

// Plans admin CRUD (Phase 4c-2). GET /plans (reader.go) is cheapest-first
// (price_cents ASC); the ADMIN findAll orders by created_at ASC — see
// Node plansService.findAll() (`order: { created_at: 'ASC' }`). The
// billing_period column is the plans_billing_period_enum; sqlc types it as
// the generated PlansBillingPeriodEnum, so InsertPlan binds the enum value
// directly (no SQL cast needed — the param already carries the enum type).
func (q *Queries) ListAllPlans(ctx context.Context) ([]ListAllPlansRow, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPlansRow{}
	for rows.Next() {
		var i ListAllPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DailyLimit,
			&i.PriceCents,
			&i.Currency,
			&i.StripePriceID,
			&i.TrialDays,
			&i.BillingPeriod,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlan = `-- name: SoftDeletePlan :exec
UPDATE plans SET is_active = false WHERE id = $1
`

func (q *Queries) SoftDeletePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePlan, id)
	return err
}
