// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Selects the active default AI provider. NestJS picks the same row in
	// AiProvidersService.findActive — keep the ORDER BY in sync there + here
	// (is_default DESC, is_active = TRUE).
	ActiveAIProvider(ctx context.Context) (ActiveAIProviderRow, error)
	// Today's daily-quota tally for the user. Compared against
	// plan.daily_limit in the application layer (so the limit can come
	// from a fallback when the user has no subscription).
	CountTodayUsage(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Mirrors usageService.countTodayByUser: rows since local midnight.
	// The caller passes the midnight boundary so timezone handling matches
	// the Node process (new Date(); setHours(0,0,0,0)).
	CountUsageToday(ctx context.Context, arg CountUsageTodayParams) (int64, error)
	CreateFreeSubscription(ctx context.Context, arg CreateFreeSubscriptionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindFreePlan(ctx context.Context) (FindFreePlanRow, error)
	FindUserByAppleId(ctx context.Context, appleID *string) (FindUserByAppleIdRow, error)
	FindUserByFacebookId(ctx context.Context, facebookID *string) (FindUserByFacebookIdRow, error)
	FindUserByGoogleId(ctx context.Context, googleID *string) (FindUserByGoogleIdRow, error)
	FindUserByTiktokId(ctx context.Context, tiktokID *string) (FindUserByTiktokIdRow, error)
	// Queries for the /rewrite microservice's Postgres adapter.
	// sqlc compiles these against schema.sql at build time; mistakes are
	// caught BEFORE the service ever boots (Rule #1 — compile-time over
	// runtime).
	//
	// Each query has three sqlc directives:
	//   :one  → returns exactly one row (errors if zero)
	//   :many → returns a slice of rows
	//   :exec → no rows; returns affected-row count
	//
	// Naming convention: <Verb><Subject>, mirrors Go function names sqlc
	// generates (FindUserWithPlan, IncrementUsageToday, …).
	// Resolves user + their active subscription's plan in one query so the
	// quota check is a single round-trip. LEFT JOIN because users without
	// an active subscription fall back to the free tier (plan_id NULL).
	// Filter on subscriptions.status = 'active' so cancelled subs don't
	// still grant their old plan.
	FindUserWithPlan(ctx context.Context, id pgtype.UUID) (FindUserWithPlanRow, error)
	// Mirrors subscriptionsService.findActiveByUserId: newest ACTIVE
	// subscription for the user, joined to its plan. ORDER BY created_at
	// DESC + LIMIT 1 reproduces TypeORM order:{created_at:'DESC'} findOne.
	GetActiveSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetActiveSubscriptionByUserIDRow, error)
	// The single app_settings row's token lifetimes. No row → caller uses
	// defaults (15 / 90), matching Node's `?? 15` / `?? 90`.
	GetAuthTokenSettings(ctx context.Context) (GetAuthTokenSettingsRow, error)
	// Phase 1a auth queries. Read the live NestJS-owned schema as-is.
	// Full projection for /auth/login. password_hash is nullable
	// (social-only accounts have none). No email normalization — Node's
	// login passes the email through unchanged.
	GetAuthUserByEmail(ctx context.Context, email string) (GetAuthUserByEmailRow, error)
	// Same projection keyed by id — used by refresh, change-password, account.
	GetAuthUserByID(ctx context.Context, id pgtype.UUID) (GetAuthUserByIDRow, error)
	// The single app_settings row's client_log_level, surfaced by
	// GET /health. There is exactly one settings row (Node does
	// `findOne({ where: {} })`); LIMIT 1 matches that.
	GetClientLogLevel(ctx context.Context) (string, error)
	// app_settings creds: both columns are NOT NULL (default '').
	GetEmailSettings(ctx context.Context) (GetEmailSettingsRow, error)
	// DB template override. PK column is template_key (not key).
	GetEmailTemplateByKey(ctx context.Context, templateKey string) (GetEmailTemplateByKeyRow, error)
	GetUserAuthState(ctx context.Context, email string) (GetUserAuthStateRow, error)
	// Phase 0 core-endpoint queries (health + /auth/me). Kept separate
	// from the rewrite module's queries.sql so the core package depends on
	// the shared sqlc types only, never on a feature module.
	// Minimal user projection for GET /auth/me — id, email, role. Mirrors
	// the fields Node's /auth/me returns from the JWT-resolved user.
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// Audit row for every deliver attempt (suppressed/skipped/sent/failed).
	InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) error
	// Records one /rewrite call for daily quota tracking + analytics.
	// Mirrors NestJS UsageService.log: same columns, same names, same
	// precision so the two backends populate identical rows.
	InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) error
	// Lowercased-email suppression check (bounce/complaint list).
	IsEmailSuppressed(ctx context.Context, email string) (bool, error)
	LinkSocialApple(ctx context.Context, arg LinkSocialAppleParams) error
	LinkSocialFacebook(ctx context.Context, arg LinkSocialFacebookParams) error
	LinkSocialGoogle(ctx context.Context, arg LinkSocialGoogleParams) error
	LinkSocialTiktok(ctx context.Context, arg LinkSocialTiktokParams) error
	// Mirrors plansService.findAll(): every active plan, cheapest first.
	// No tiebreaker beyond price_cents (matches TypeORM order:{price_cents:'ASC'}).
	ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error)
	ResetPasswordHash(ctx context.Context, arg ResetPasswordHashParams) error
	SetEmailVerificationCode(ctx context.Context, arg SetEmailVerificationCodeParams) error
	SetPasswordResetAttempts(ctx context.Context, arg SetPasswordResetAttemptsParams) error
	SetPasswordResetCode(ctx context.Context, arg SetPasswordResetCodeParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) error
}

var _ Querier = (*Queries)(nil)
