// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_errors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpErrorReport = `-- name: BumpErrorReport :one
UPDATE error_reports SET
  count = count + 1,
  last_seen_at = now(),
  app_version = COALESCE($2, app_version),
  user_id = COALESCE($3, user_id),
  device_id = COALESCE($4, device_id),
  context = COALESCE($5, context)
WHERE fingerprint = $1
RETURNING id, display_no, count, first_seen_at
`

type BumpErrorReportParams struct {
	Fingerprint string      `db:"fingerprint" json:"fingerprint"`
	AppVersion  *string     `db:"app_version" json:"app_version"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID    *string     `db:"device_id" json:"device_id"`
	Context     []byte      `db:"context" json:"context"`
}

type BumpErrorReportRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	DisplayNo   int64              `db:"display_no" json:"display_no"`
	Count       int32              `db:"count" json:"count"`
	FirstSeenAt pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
}

func (q *Queries) BumpErrorReport(ctx context.Context, arg BumpErrorReportParams) (BumpErrorReportRow, error) {
	row := q.db.QueryRow(ctx, bumpErrorReport,
		arg.Fingerprint,
		arg.AppVersion,
		arg.UserID,
		arg.DeviceID,
		arg.Context,
	)
	var i BumpErrorReportRow
	err := row.Scan(
		&i.ID,
		&i.DisplayNo,
		&i.Count,
		&i.FirstSeenAt,
	)
	return i, err
}

const findErrorByFingerprint = `-- name: FindErrorByFingerprint :one

SELECT id, platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status, ai_fix_proposal, resolved_by, resolved_at, first_seen_at, last_seen_at, display_no FROM error_reports WHERE fingerprint = $1
`

// internal/shared/pg/queries_errors.sql
// Crash-report ingest: read-then-write dedup (no ON CONFLICT, matching Node).
func (q *Queries) FindErrorByFingerprint(ctx context.Context, fingerprint string) (ErrorReport, error) {
	row := q.db.QueryRow(ctx, findErrorByFingerprint, fingerprint)
	var i ErrorReport
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AppVersion,
		&i.Severity,
		&i.ErrorType,
		&i.Message,
		&i.StackTrace,
		&i.Context,
		&i.UserID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.Count,
		&i.Status,
		&i.AiFixProposal,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.DisplayNo,
	)
	return i, err
}

const insertErrorReport = `-- name: InsertErrorReport :one
INSERT INTO error_reports
  (platform, app_version, severity, error_type, message, stack_trace, context, user_id, device_id, fingerprint, count, status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1,0)
RETURNING id, display_no, count, first_seen_at
`

type InsertErrorReportParams struct {
	Platform    string      `db:"platform" json:"platform"`
	AppVersion  *string     `db:"app_version" json:"app_version"`
	Severity    string      `db:"severity" json:"severity"`
	ErrorType   *string     `db:"error_type" json:"error_type"`
	Message     *string     `db:"message" json:"message"`
	StackTrace  *string     `db:"stack_trace" json:"stack_trace"`
	Context     []byte      `db:"context" json:"context"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID    *string     `db:"device_id" json:"device_id"`
	Fingerprint string      `db:"fingerprint" json:"fingerprint"`
}

type InsertErrorReportRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	DisplayNo   int64              `db:"display_no" json:"display_no"`
	Count       int32              `db:"count" json:"count"`
	FirstSeenAt pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
}

func (q *Queries) InsertErrorReport(ctx context.Context, arg InsertErrorReportParams) (InsertErrorReportRow, error) {
	row := q.db.QueryRow(ctx, insertErrorReport,
		arg.Platform,
		arg.AppVersion,
		arg.Severity,
		arg.ErrorType,
		arg.Message,
		arg.StackTrace,
		arg.Context,
		arg.UserID,
		arg.DeviceID,
		arg.Fingerprint,
	)
	var i InsertErrorReportRow
	err := row.Scan(
		&i.ID,
		&i.DisplayNo,
		&i.Count,
		&i.FirstSeenAt,
	)
	return i, err
}
