// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsageToday = `-- name: CountUsageToday :one
SELECT COUNT(*) FROM usage_logs
WHERE user_id = $1 AND created_at >= $2
`

type CountUsageTodayParams struct {
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

// Mirrors usageService.countTodayByUser: rows since local midnight.
// The caller passes the midnight boundary so timezone handling matches
// the Node process (new Date(); setHours(0,0,0,0)).
func (q *Queries) CountUsageToday(ctx context.Context, arg CountUsageTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageToday, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSubscriptionByUserID = `-- name: GetActiveSubscriptionByUserID :one
SELECT s.status, s.store_type, s.started_at, s.expires_at,
       p.name AS plan_name, p.daily_limit
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1 AND s.status = 'active'::subscriptions_status_enum
ORDER BY s.created_at DESC
LIMIT 1
`

type GetActiveSubscriptionByUserIDRow struct {
	Status     SubscriptionsStatusEnum    `db:"status" json:"status"`
	StoreType  SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StartedAt  pgtype.Timestamp           `db:"started_at" json:"started_at"`
	ExpiresAt  pgtype.Timestamp           `db:"expires_at" json:"expires_at"`
	PlanName   string                     `db:"plan_name" json:"plan_name"`
	DailyLimit int32                      `db:"daily_limit" json:"daily_limit"`
}

// Mirrors subscriptionsService.findActiveByUserId: newest ACTIVE
// subscription for the user, joined to its plan. ORDER BY created_at
// DESC + LIMIT 1 reproduces TypeORM order:{created_at:'DESC'} findOne.
func (q *Queries) GetActiveSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetActiveSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUserID, userID)
	var i GetActiveSubscriptionByUserIDRow
	err := row.Scan(
		&i.Status,
		&i.StoreType,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.PlanName,
		&i.DailyLimit,
	)
	return i, err
}

const getAuthTokenSettings = `-- name: GetAuthTokenSettings :one
SELECT token_expiry_minutes, refresh_token_expiry_days
FROM app_settings
LIMIT 1
`

type GetAuthTokenSettingsRow struct {
	TokenExpiryMinutes     int32 `db:"token_expiry_minutes" json:"token_expiry_minutes"`
	RefreshTokenExpiryDays int32 `db:"refresh_token_expiry_days" json:"refresh_token_expiry_days"`
}

// The single app_settings row's token lifetimes. No row → caller uses
// defaults (15 / 90), matching Node's `?? 15` / `?? 90`.
func (q *Queries) GetAuthTokenSettings(ctx context.Context) (GetAuthTokenSettingsRow, error) {
	row := q.db.QueryRow(ctx, getAuthTokenSettings)
	var i GetAuthTokenSettingsRow
	err := row.Scan(&i.TokenExpiryMinutes, &i.RefreshTokenExpiryDays)
	return i, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one

SELECT id, email, password_hash, name, is_active, role,
       auth_provider, email_verified, lemonsqueezy_customer_id
FROM users
WHERE email = $1
LIMIT 1
`

type GetAuthUserByEmailRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
}

// Phase 1a auth queries. Read the live NestJS-owned schema as-is.
// Full projection for /auth/login. password_hash is nullable
// (social-only accounts have none). No email normalization — Node's
// login passes the email through unchanged.
func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (GetAuthUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i GetAuthUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, email, password_hash, name, is_active, role,
       auth_provider, email_verified, lemonsqueezy_customer_id
FROM users
WHERE id = $1
LIMIT 1
`

type GetAuthUserByIDRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
}

// Same projection keyed by id — used by refresh, change-password, account.
func (q *Queries) GetAuthUserByID(ctx context.Context, id pgtype.UUID) (GetAuthUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i GetAuthUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
