// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_exttoken.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveTokenByHash = `-- name: FindActiveTokenByHash :one
SELECT id, user_id, scopes, revoked_at
FROM extension_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
LIMIT 1
`

type FindActiveTokenByHashRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Scopes    []string         `db:"scopes" json:"scopes"`
	RevokedAt pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
}

// validate(): resolve a presented token's hash to owner + scopes. Returns id
// too — Verify (T13) fires TouchTokenLastUsed by id afterwards.
func (q *Queries) FindActiveTokenByHash(ctx context.Context, tokenHash string) (FindActiveTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findActiveTokenByHash, tokenHash)
	var i FindActiveTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scopes,
		&i.RevokedAt,
	)
	return i, err
}

const insertExtensionToken = `-- name: InsertExtensionToken :one
INSERT INTO extension_tokens (user_id, token_hash, scopes, device_id, device_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, scopes, device_id, device_name, last_used_at, created_at, revoked_at
`

type InsertExtensionTokenParams struct {
	UserID     pgtype.UUID `db:"user_id" json:"user_id"`
	TokenHash  string      `db:"token_hash" json:"token_hash"`
	Scopes     []string    `db:"scopes" json:"scopes"`
	DeviceID   pgtype.UUID `db:"device_id" json:"device_id"`
	DeviceName string      `db:"device_name" json:"device_name"`
}

type InsertExtensionTokenRow struct {
	ID         pgtype.UUID      `db:"id" json:"id"`
	Scopes     []string         `db:"scopes" json:"scopes"`
	DeviceID   pgtype.UUID      `db:"device_id" json:"device_id"`
	DeviceName string           `db:"device_name" json:"device_name"`
	LastUsedAt pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	RevokedAt  pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
}

// mint() insert. Returns the projection list() serializes (token_hash and
// user_id stripped by the controller, so omitted here).
func (q *Queries) InsertExtensionToken(ctx context.Context, arg InsertExtensionTokenParams) (InsertExtensionTokenRow, error) {
	row := q.db.QueryRow(ctx, insertExtensionToken,
		arg.UserID,
		arg.TokenHash,
		arg.Scopes,
		arg.DeviceID,
		arg.DeviceName,
	)
	var i InsertExtensionTokenRow
	err := row.Scan(
		&i.ID,
		&i.Scopes,
		&i.DeviceID,
		&i.DeviceName,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveTokens = `-- name: ListActiveTokens :many
SELECT id, scopes, device_id, device_name, last_used_at, created_at, revoked_at
FROM extension_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListActiveTokensRow struct {
	ID         pgtype.UUID      `db:"id" json:"id"`
	Scopes     []string         `db:"scopes" json:"scopes"`
	DeviceID   pgtype.UUID      `db:"device_id" json:"device_id"`
	DeviceName string           `db:"device_name" json:"device_name"`
	LastUsedAt pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	CreatedAt  pgtype.Timestamp `db:"created_at" json:"created_at"`
	RevokedAt  pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
}

// list(): active tokens for the user, newest first
// (TypeORM where:{user_id, revoked_at:IsNull()} order:{created_at:'DESC'}).
func (q *Queries) ListActiveTokens(ctx context.Context, userID pgtype.UUID) ([]ListActiveTokensRow, error) {
	rows, err := q.db.Query(ctx, listActiveTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTokensRow{}
	for rows.Next() {
		var i ListActiveTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Scopes,
			&i.DeviceID,
			&i.DeviceName,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveTokensForDevice = `-- name: RevokeActiveTokensForDevice :exec

UPDATE extension_tokens
SET revoked_at = now()
WHERE user_id = $1 AND device_id = $2 AND revoked_at IS NULL
`

type RevokeActiveTokensForDeviceParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceID pgtype.UUID `db:"device_id" json:"device_id"`
}

// Extension-token persistence (dr_ext_* keyboard/share tokens).
// Read the live NestJS-owned schema as-is; mirror ExtensionTokenService
// (backend/src/auth/extension-token.service.ts) WHERE semantics exactly.
// Table: public.extension_tokens — scopes text[], device_id uuid,
// timestamps "without time zone".
// mint() rotates: revoke any still-active token for this (user, device)
// first so the partial unique index idx_ext_tokens_user_device_active
// (user_id, device_id) WHERE revoked_at IS NULL doesn't collide.
func (q *Queries) RevokeActiveTokensForDevice(ctx context.Context, arg RevokeActiveTokensForDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeActiveTokensForDevice, arg.UserID, arg.DeviceID)
	return err
}

const revokeTokenByID = `-- name: RevokeTokenByID :exec
UPDATE extension_tokens
SET revoked_at = now()
WHERE id = $1 AND user_id = $2
`

type RevokeTokenByIDParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

// revoke(): owner-scoped UPDATE keyed by (id, user_id). Node does NOT filter
// revoked_at IS NULL here, so re-revoking an already-revoked row is a no-op
// touch of revoked_at — idempotent, controller returns 204 either way.
func (q *Queries) RevokeTokenByID(ctx context.Context, arg RevokeTokenByIDParams) error {
	_, err := q.db.Exec(ctx, revokeTokenByID, arg.ID, arg.UserID)
	return err
}

const touchTokenLastUsed = `-- name: TouchTokenLastUsed :exec
UPDATE extension_tokens SET last_used_at = now() WHERE id = $1
`

// validate() write-behind: bump last_used_at. Failures non-fatal (caller
// ignores the error so the request still succeeds).
func (q *Queries) TouchTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchTokenLastUsed, id)
	return err
}
