// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_appsettings.sql

package sqlc

import (
	"context"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT id, environment, trial_limit, token_expiry_minutes, max_input_length, supported_languages, stripe_secret_key, stripe_webhook_secret, paypal_client_id, paypal_client_secret, paypal_mode, momo_partner_code, momo_access_key, momo_secret_key, momo_mode, vietqr_bank_id, vietqr_account_number, vietqr_account_name, casso_api_key, sepay_api_key, google_client_id, google_client_secret, apple_client_id, apple_team_id, apple_key_id, updated_at, refresh_token_expiry_days, stripe_mode, sepay_mode, resend_api_key, email_from, client_log_level, payment_methods_enabled, lemonsqueezy_api_key, lemonsqueezy_store_id, lemonsqueezy_webhook_secret, lemonsqueezy_variant_monthly, lemonsqueezy_variant_yearly, paypal_webhook_id, paypal_plan_monthly, paypal_plan_yearly FROM app_settings ORDER BY updated_at ASC LIMIT 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.Environment,
		&i.TrialLimit,
		&i.TokenExpiryMinutes,
		&i.MaxInputLength,
		&i.SupportedLanguages,
		&i.StripeSecretKey,
		&i.StripeWebhookSecret,
		&i.PaypalClientID,
		&i.PaypalClientSecret,
		&i.PaypalMode,
		&i.MomoPartnerCode,
		&i.MomoAccessKey,
		&i.MomoSecretKey,
		&i.MomoMode,
		&i.VietqrBankID,
		&i.VietqrAccountNumber,
		&i.VietqrAccountName,
		&i.CassoApiKey,
		&i.SepayApiKey,
		&i.GoogleClientID,
		&i.GoogleClientSecret,
		&i.AppleClientID,
		&i.AppleTeamID,
		&i.AppleKeyID,
		&i.UpdatedAt,
		&i.RefreshTokenExpiryDays,
		&i.StripeMode,
		&i.SepayMode,
		&i.ResendApiKey,
		&i.EmailFrom,
		&i.ClientLogLevel,
		&i.PaymentMethodsEnabled,
		&i.LemonsqueezyApiKey,
		&i.LemonsqueezyStoreID,
		&i.LemonsqueezyWebhookSecret,
		&i.LemonsqueezyVariantMonthly,
		&i.LemonsqueezyVariantYearly,
		&i.PaypalWebhookID,
		&i.PaypalPlanMonthly,
		&i.PaypalPlanYearly,
	)
	return i, err
}

const insertDefaultAppSettings = `-- name: InsertDefaultAppSettings :one
INSERT INTO app_settings DEFAULT VALUES RETURNING id, environment, trial_limit, token_expiry_minutes, max_input_length, supported_languages, stripe_secret_key, stripe_webhook_secret, paypal_client_id, paypal_client_secret, paypal_mode, momo_partner_code, momo_access_key, momo_secret_key, momo_mode, vietqr_bank_id, vietqr_account_number, vietqr_account_name, casso_api_key, sepay_api_key, google_client_id, google_client_secret, apple_client_id, apple_team_id, apple_key_id, updated_at, refresh_token_expiry_days, stripe_mode, sepay_mode, resend_api_key, email_from, client_log_level, payment_methods_enabled, lemonsqueezy_api_key, lemonsqueezy_store_id, lemonsqueezy_webhook_secret, lemonsqueezy_variant_monthly, lemonsqueezy_variant_yearly, paypal_webhook_id, paypal_plan_monthly, paypal_plan_yearly
`

func (q *Queries) InsertDefaultAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRow(ctx, insertDefaultAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.Environment,
		&i.TrialLimit,
		&i.TokenExpiryMinutes,
		&i.MaxInputLength,
		&i.SupportedLanguages,
		&i.StripeSecretKey,
		&i.StripeWebhookSecret,
		&i.PaypalClientID,
		&i.PaypalClientSecret,
		&i.PaypalMode,
		&i.MomoPartnerCode,
		&i.MomoAccessKey,
		&i.MomoSecretKey,
		&i.MomoMode,
		&i.VietqrBankID,
		&i.VietqrAccountNumber,
		&i.VietqrAccountName,
		&i.CassoApiKey,
		&i.SepayApiKey,
		&i.GoogleClientID,
		&i.GoogleClientSecret,
		&i.AppleClientID,
		&i.AppleTeamID,
		&i.AppleKeyID,
		&i.UpdatedAt,
		&i.RefreshTokenExpiryDays,
		&i.StripeMode,
		&i.SepayMode,
		&i.ResendApiKey,
		&i.EmailFrom,
		&i.ClientLogLevel,
		&i.PaymentMethodsEnabled,
		&i.LemonsqueezyApiKey,
		&i.LemonsqueezyStoreID,
		&i.LemonsqueezyWebhookSecret,
		&i.LemonsqueezyVariantMonthly,
		&i.LemonsqueezyVariantYearly,
		&i.PaypalWebhookID,
		&i.PaypalPlanMonthly,
		&i.PaypalPlanYearly,
	)
	return i, err
}
