// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_core.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClientLogLevel = `-- name: GetClientLogLevel :one
SELECT client_log_level
FROM app_settings
LIMIT 1
`

// The single app_settings row's client_log_level, surfaced by
// GET /health. There is exactly one settings row (Node does
// `findOne({ where: {} })`); LIMIT 1 matches that.
func (q *Queries) GetClientLogLevel(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getClientLogLevel)
	var client_log_level string
	err := row.Scan(&client_log_level)
	return client_log_level, err
}

const getPaymentCredentials = `-- name: GetPaymentCredentials :one
SELECT stripe_secret_key,
       vietqr_bank_id,
       vietqr_account_number,
       vietqr_account_name,
       lemonsqueezy_api_key,
       lemonsqueezy_store_id,
       lemonsqueezy_variant_monthly,
       lemonsqueezy_variant_yearly
FROM app_settings
LIMIT 1
`

type GetPaymentCredentialsRow struct {
	StripeSecretKey            string `db:"stripe_secret_key" json:"stripe_secret_key"`
	VietqrBankID               string `db:"vietqr_bank_id" json:"vietqr_bank_id"`
	VietqrAccountNumber        string `db:"vietqr_account_number" json:"vietqr_account_number"`
	VietqrAccountName          string `db:"vietqr_account_name" json:"vietqr_account_name"`
	LemonsqueezyApiKey         string `db:"lemonsqueezy_api_key" json:"lemonsqueezy_api_key"`
	LemonsqueezyStoreID        string `db:"lemonsqueezy_store_id" json:"lemonsqueezy_store_id"`
	LemonsqueezyVariantMonthly string `db:"lemonsqueezy_variant_monthly" json:"lemonsqueezy_variant_monthly"`
	LemonsqueezyVariantYearly  string `db:"lemonsqueezy_variant_yearly" json:"lemonsqueezy_variant_yearly"`
}

// Checkout-time provider credentials from the singleton app_settings row.
// All columns are NOT NULL DEFAULT ”. No row → pgx.ErrNoRows (caller treats
// as all-empty → env fallback per resolveCredential).
func (q *Queries) GetPaymentCredentials(ctx context.Context) (GetPaymentCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getPaymentCredentials)
	var i GetPaymentCredentialsRow
	err := row.Scan(
		&i.StripeSecretKey,
		&i.VietqrBankID,
		&i.VietqrAccountNumber,
		&i.VietqrAccountName,
		&i.LemonsqueezyApiKey,
		&i.LemonsqueezyStoreID,
		&i.LemonsqueezyVariantMonthly,
		&i.LemonsqueezyVariantYearly,
	)
	return i, err
}

const getPaymentMethodsEnabled = `-- name: GetPaymentMethodsEnabled :one
SELECT payment_methods_enabled FROM app_settings LIMIT 1
`

// payment_methods_enabled CSV from the singleton app_settings row. NOT NULL
// (default ”); empty string means unconfigured → caller falls back to env
// then default. No row at all → pgx.ErrNoRows, mapped to found=false.
func (q *Queries) GetPaymentMethodsEnabled(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodsEnabled)
	var payment_methods_enabled string
	err := row.Scan(&payment_methods_enabled)
	return payment_methods_enabled, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, role
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID    pgtype.UUID   `db:"id" json:"id"`
	Email string        `db:"email" json:"email"`
	Role  UsersRoleEnum `db:"role" json:"role"`
}

// Phase 0 core-endpoint queries (health + /auth/me). Kept separate
// from the rewrite module's queries.sql so the core package depends on
// the shared sqlc types only, never on a feature module.
// Minimal user projection for GET /auth/me — id, email, role. Mirrors
// the fields Node's /auth/me returns from the JWT-resolved user.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}
