// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_users_admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserFull = `-- name: GetUserFull :one

SELECT id, email, password_hash, name, is_active, role, auth_provider,
       google_id, facebook_id, tiktok_id, apple_id, avatar_url,
       stripe_customer_id, email_verified, email_verification_code,
       email_verification_expires, password_reset_code, password_reset_expires,
       password_reset_attempts, lemonsqueezy_customer_id, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserFullRow struct {
	ID                       pgtype.UUID           `db:"id" json:"id"`
	Email                    string                `db:"email" json:"email"`
	PasswordHash             *string               `db:"password_hash" json:"password_hash"`
	Name                     string                `db:"name" json:"name"`
	IsActive                 bool                  `db:"is_active" json:"is_active"`
	Role                     UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider             UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	GoogleID                 *string               `db:"google_id" json:"google_id"`
	FacebookID               *string               `db:"facebook_id" json:"facebook_id"`
	TiktokID                 *string               `db:"tiktok_id" json:"tiktok_id"`
	AppleID                  *string               `db:"apple_id" json:"apple_id"`
	AvatarUrl                *string               `db:"avatar_url" json:"avatar_url"`
	StripeCustomerID         *string               `db:"stripe_customer_id" json:"stripe_customer_id"`
	EmailVerified            bool                  `db:"email_verified" json:"email_verified"`
	EmailVerificationCode    *string               `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz    `db:"email_verification_expires" json:"email_verification_expires"`
	PasswordResetCode        *string               `db:"password_reset_code" json:"password_reset_code"`
	PasswordResetExpires     pgtype.Timestamptz    `db:"password_reset_expires" json:"password_reset_expires"`
	PasswordResetAttempts    int32                 `db:"password_reset_attempts" json:"password_reset_attempts"`
	LemonsqueezyCustomerID   *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	CreatedAt                pgtype.Timestamp      `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamp      `db:"updated_at" json:"updated_at"`
}

// Admin user CRUD (Phase 4c-2). GET /admin/users/:id returns the FULL
// TypeORM User entity (the `user` field); PATCH /admin/users/:id re-reads
// it. Only the full-row GET is static — the bespoke paginated list, its
// COUNT, and the partial UPDATE have runtime WHERE/ORDER/SET and so are
// assembled in Go on the pool (NOT here). Columns are listed in
// entity-declaration order (src/users/entities/user.entity.ts) so the
// scan lines up with user.UserDetail. The two nullable timestamps are
// timestamptz; the two non-null timestamps are timestamp.
func (q *Queries) GetUserFull(ctx context.Context, id pgtype.UUID) (GetUserFullRow, error) {
	row := q.db.QueryRow(ctx, getUserFull, id)
	var i GetUserFullRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.GoogleID,
		&i.FacebookID,
		&i.TiktokID,
		&i.AppleID,
		&i.AvatarUrl,
		&i.StripeCustomerID,
		&i.EmailVerified,
		&i.EmailVerificationCode,
		&i.EmailVerificationExpires,
		&i.PasswordResetCode,
		&i.PasswordResetExpires,
		&i.PasswordResetAttempts,
		&i.LemonsqueezyCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
