// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_bugreports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminBugFixCandidates = `-- name: AdminBugFixCandidates :many
SELECT id, source, description, screenshot_path, screenshot_filename, app_version, os_info, user_id, user_email, context, status, admin_notes, created_at, updated_at, ai_fix_proposal, ai_fix_proposed_at, kind, title, target_platform, vote_count, is_public, display_no FROM bug_reports
WHERE status = 'new' AND kind = 'bug' AND ai_fix_proposal IS NULL
ORDER BY created_at DESC
LIMIT $1
`

// Cron: status='new' AND kind='bug' AND ai_fix_proposal IS NULL,
// ORDER BY created_at DESC, LIMIT $1 (5 per run).
func (q *Queries) AdminBugFixCandidates(ctx context.Context, limit int32) ([]BugReport, error) {
	rows, err := q.db.Query(ctx, adminBugFixCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BugReport{}
	for rows.Next() {
		var i BugReport
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Description,
			&i.ScreenshotPath,
			&i.ScreenshotFilename,
			&i.AppVersion,
			&i.OsInfo,
			&i.UserID,
			&i.UserEmail,
			&i.Context,
			&i.Status,
			&i.AdminNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AiFixProposal,
			&i.AiFixProposedAt,
			&i.Kind,
			&i.Title,
			&i.TargetPlatform,
			&i.VoteCount,
			&i.IsPublic,
			&i.DisplayNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDeleteBugReport = `-- name: AdminDeleteBugReport :execrows
DELETE FROM bug_reports WHERE id = $1
`

func (q *Queries) AdminDeleteBugReport(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteBugReport, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetBugReport = `-- name: AdminGetBugReport :one

SELECT id, source, description, screenshot_path, screenshot_filename, app_version, os_info, user_id, user_email, context, status, admin_notes, created_at, updated_at, ai_fix_proposal, ai_fix_proposed_at, kind, title, target_platform, vote_count, is_public, display_no FROM bug_reports WHERE id = $1
`

// Admin triage (GET/:id, DELETE/:id, PATCH/:id, fix-proposal, cron).
// The admin LIST (GET /admin/bug-reports) is a parseListQuery consumer with
// dynamic WHERE/ORDER → assembled in Go on the pgxpool (admin_repo_pg.go),
// NOT a static sqlc query.
func (q *Queries) AdminGetBugReport(ctx context.Context, id pgtype.UUID) (BugReport, error) {
	row := q.db.QueryRow(ctx, adminGetBugReport, id)
	var i BugReport
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Description,
		&i.ScreenshotPath,
		&i.ScreenshotFilename,
		&i.AppVersion,
		&i.OsInfo,
		&i.UserID,
		&i.UserEmail,
		&i.Context,
		&i.Status,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiFixProposal,
		&i.AiFixProposedAt,
		&i.Kind,
		&i.Title,
		&i.TargetPlatform,
		&i.VoteCount,
		&i.IsPublic,
		&i.DisplayNo,
	)
	return i, err
}

const adminSetBugFixProposal = `-- name: AdminSetBugFixProposal :one
UPDATE bug_reports
SET ai_fix_proposal = $2, ai_fix_proposed_at = $3, status = $4, updated_at = now()
WHERE id = $1
RETURNING id, source, description, screenshot_path, screenshot_filename, app_version, os_info, user_id, user_email, context, status, admin_notes, created_at, updated_at, ai_fix_proposal, ai_fix_proposed_at, kind, title, target_platform, vote_count, is_public, display_no
`

type AdminSetBugFixProposalParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	AiFixProposal   *string            `db:"ai_fix_proposal" json:"ai_fix_proposal"`
	AiFixProposedAt pgtype.Timestamptz `db:"ai_fix_proposed_at" json:"ai_fix_proposed_at"`
	Status          *string            `db:"status" json:"status"`
}

func (q *Queries) AdminSetBugFixProposal(ctx context.Context, arg AdminSetBugFixProposalParams) (BugReport, error) {
	row := q.db.QueryRow(ctx, adminSetBugFixProposal,
		arg.ID,
		arg.AiFixProposal,
		arg.AiFixProposedAt,
		arg.Status,
	)
	var i BugReport
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Description,
		&i.ScreenshotPath,
		&i.ScreenshotFilename,
		&i.AppVersion,
		&i.OsInfo,
		&i.UserID,
		&i.UserEmail,
		&i.Context,
		&i.Status,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiFixProposal,
		&i.AiFixProposedAt,
		&i.Kind,
		&i.Title,
		&i.TargetPlatform,
		&i.VoteCount,
		&i.IsPublic,
		&i.DisplayNo,
	)
	return i, err
}

const adminUpdateBugReport = `-- name: AdminUpdateBugReport :one
UPDATE bug_reports
SET status = $2, admin_notes = $3, title = $4, target_platform = $5, is_public = $6, updated_at = now()
WHERE id = $1
RETURNING id, source, description, screenshot_path, screenshot_filename, app_version, os_info, user_id, user_email, context, status, admin_notes, created_at, updated_at, ai_fix_proposal, ai_fix_proposed_at, kind, title, target_platform, vote_count, is_public, display_no
`

type AdminUpdateBugReportParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	Status         *string     `db:"status" json:"status"`
	AdminNotes     *string     `db:"admin_notes" json:"admin_notes"`
	Title          *string     `db:"title" json:"title"`
	TargetPlatform *string     `db:"target_platform" json:"target_platform"`
	IsPublic       bool        `db:"is_public" json:"is_public"`
}

// The use case (admin_usecase.go) does the partial-merge in Go (load → apply
// only the provided DTO fields → write the merged values), mirroring Node's
// per-field `if (dto.x !== undefined)`. This writes the already-merged values.
func (q *Queries) AdminUpdateBugReport(ctx context.Context, arg AdminUpdateBugReportParams) (BugReport, error) {
	row := q.db.QueryRow(ctx, adminUpdateBugReport,
		arg.ID,
		arg.Status,
		arg.AdminNotes,
		arg.Title,
		arg.TargetPlatform,
		arg.IsPublic,
	)
	var i BugReport
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Description,
		&i.ScreenshotPath,
		&i.ScreenshotFilename,
		&i.AppVersion,
		&i.OsInfo,
		&i.UserID,
		&i.UserEmail,
		&i.Context,
		&i.Status,
		&i.AdminNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiFixProposal,
		&i.AiFixProposedAt,
		&i.Kind,
		&i.Title,
		&i.TargetPlatform,
		&i.VoteCount,
		&i.IsPublic,
		&i.DisplayNo,
	)
	return i, err
}

const insertBugReport = `-- name: InsertBugReport :one
INSERT INTO bug_reports
  (source, description, screenshot_path, screenshot_filename, app_version,
   os_info, user_id, user_email, context, status, kind)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'new','bug')
RETURNING id, display_no
`

type InsertBugReportParams struct {
	Source             string      `db:"source" json:"source"`
	Description        string      `db:"description" json:"description"`
	ScreenshotPath     *string     `db:"screenshot_path" json:"screenshot_path"`
	ScreenshotFilename *string     `db:"screenshot_filename" json:"screenshot_filename"`
	AppVersion         *string     `db:"app_version" json:"app_version"`
	OsInfo             *string     `db:"os_info" json:"os_info"`
	UserID             pgtype.UUID `db:"user_id" json:"user_id"`
	UserEmail          *string     `db:"user_email" json:"user_email"`
	Context            []byte      `db:"context" json:"context"`
}

type InsertBugReportRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	DisplayNo int64       `db:"display_no" json:"display_no"`
}

func (q *Queries) InsertBugReport(ctx context.Context, arg InsertBugReportParams) (InsertBugReportRow, error) {
	row := q.db.QueryRow(ctx, insertBugReport,
		arg.Source,
		arg.Description,
		arg.ScreenshotPath,
		arg.ScreenshotFilename,
		arg.AppVersion,
		arg.OsInfo,
		arg.UserID,
		arg.UserEmail,
		arg.Context,
	)
	var i InsertBugReportRow
	err := row.Scan(&i.ID, &i.DisplayNo)
	return i, err
}

const userExists = `-- name: UserExists :one

SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

// internal/shared/pg/queries_bugreports.sql
// Public bug-report ingest (POST /bug-reports, multipart with optional
// screenshot). user_id is nulled when the JWT outlives its user.
func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
