// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_usercontext.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserContext = `-- name: GetUserContext :one

SELECT enabled, job_title, industry, audience, style_notes
FROM user_contexts
WHERE user_id = $1
`

type GetUserContextRow struct {
	Enabled    bool   `db:"enabled" json:"enabled"`
	JobTitle   string `db:"job_title" json:"job_title"`
	Industry   string `db:"industry" json:"industry"`
	Audience   string `db:"audience" json:"audience"`
	StyleNotes string `db:"style_notes" json:"style_notes"`
}

// Per-user rewrite personalization context (#173). Read-only on the Go side:
// the profile is written by the NestJS /me/context endpoints; Go only reads it
// to inject the preamble at rewrite time. style_notes comes back encrypted
// (enc:v1:) and is decrypted in the adapter via secretcipher.
func (q *Queries) GetUserContext(ctx context.Context, userID pgtype.UUID) (GetUserContextRow, error) {
	row := q.db.QueryRow(ctx, getUserContext, userID)
	var i GetUserContextRow
	err := row.Scan(
		&i.Enabled,
		&i.JobTitle,
		&i.Industry,
		&i.Audience,
		&i.StyleNotes,
	)
	return i, err
}
