// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_adminusers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminEmailExists = `-- name: AdminEmailExists :one
SELECT EXISTS(SELECT 1 FROM admin_users WHERE email = $1)
`

func (q *Queries) AdminEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, adminEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveAdminUsers = `-- name: CountActiveAdminUsers :one
SELECT COUNT(*) FROM admin_users WHERE is_active = true
`

func (q *Queries) CountActiveAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminUserAudit = `-- name: CountAdminUserAudit :one
SELECT COUNT(*) FROM admin_user_audit_log
`

func (q *Queries) CountAdminUserAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUserAudit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminUserEmailByID = `-- name: GetAdminUserEmailByID :one

SELECT email FROM admin_users WHERE id = $1
`

// #51 audit log. GetAdminUserEmailByID snapshots actor/target email inside the
// soft-delete tx. InsertAdminUserAudit writes the append-only row in that same
// tx. List/Count back GET /admin/admin-user-audit (Go-only, newest-first).
func (q *Queries) GetAdminUserEmailByID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAdminUserEmailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getAdminUserIsActiveByID = `-- name: GetAdminUserIsActiveByID :one
SELECT is_active FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUserIsActiveByID(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getAdminUserIsActiveByID, id)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const insertAdminUser = `-- name: InsertAdminUser :one
INSERT INTO admin_users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, is_active, role, created_at, updated_at
`

type InsertAdminUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Name         string `db:"name" json:"name"`
	Role         string `db:"role" json:"role"`
}

type InsertAdminUserRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Email     string           `db:"email" json:"email"`
	Name      string           `db:"name" json:"name"`
	IsActive  bool             `db:"is_active" json:"is_active"`
	Role      string           `db:"role" json:"role"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (InsertAdminUserRow, error) {
	row := q.db.QueryRow(ctx, insertAdminUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i InsertAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdminUserAudit = `-- name: InsertAdminUserAudit :exec
INSERT INTO admin_user_audit_log (actor_admin_id, actor_email, target_admin_id, target_email)
VALUES ($1, $2, $3, $4)
`

type InsertAdminUserAuditParams struct {
	ActorAdminID  pgtype.UUID `db:"actor_admin_id" json:"actor_admin_id"`
	ActorEmail    string      `db:"actor_email" json:"actor_email"`
	TargetAdminID pgtype.UUID `db:"target_admin_id" json:"target_admin_id"`
	TargetEmail   string      `db:"target_email" json:"target_email"`
}

func (q *Queries) InsertAdminUserAudit(ctx context.Context, arg InsertAdminUserAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminUserAudit,
		arg.ActorAdminID,
		arg.ActorEmail,
		arg.TargetAdminID,
		arg.TargetEmail,
	)
	return err
}

const listAdminUserAudit = `-- name: ListAdminUserAudit :many
SELECT id, actor_admin_id, actor_email, target_admin_id, target_email, created_at
FROM admin_user_audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminUserAuditParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAdminUserAudit(ctx context.Context, arg ListAdminUserAuditParams) ([]AdminUserAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminUserAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserAuditLog{}
	for rows.Next() {
		var i AdminUserAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorAdminID,
			&i.ActorEmail,
			&i.TargetAdminID,
			&i.TargetEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many

SELECT id, email, name, is_active, role, created_at, updated_at
FROM admin_users ORDER BY created_at ASC
`

type ListAdminUsersRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Email     string           `db:"email" json:"email"`
	Name      string           `db:"name" json:"name"`
	IsActive  bool             `db:"is_active" json:"is_active"`
	Role      string           `db:"role" json:"role"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Admin-users CRUD (Phase 4c-2). The bare full-list, INSERT, soft-delete,
// and exact-email dup-check are static; the paginated branch + partial
// UPDATE have runtime WHERE/ORDER/SET assembled in Go on the pool.
// Bare list orders created_at ASC (Node adminUserRepo.find order ASC).
// Every projection omits password_hash so the secret never leaves the DB.
func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsActive,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAdminUser = `-- name: SoftDeleteAdminUser :exec
UPDATE admin_users SET is_active = false WHERE id = $1
`

func (q *Queries) SoftDeleteAdminUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAdminUser, id)
	return err
}
