// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPayment = `-- name: ConfirmPayment :exec
UPDATE payments SET status = 'completed', completed_at = $2, notes = $3, updated_at = NOW()
WHERE id = $1
`

type ConfirmPaymentParams struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	CompletedAt pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	Notes       *string          `db:"notes" json:"notes"`
}

// adminConfirm(paymentId, adminNotes): flip a pending payment to completed,
// stamping completed_at + notes (Node sets status=COMPLETED, completed_at=new
// Date(), notes=adminNotes||'Manually confirmed by admin' then save()). The
// completed_at + notes are bound ($2,$3) — the use case computes them (now()
// injected for deterministic tests; notes already defaulted).
func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) error {
	_, err := q.db.Exec(ctx, confirmPayment, arg.ID, arg.CompletedAt, arg.Notes)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, plan_id, amount, currency, method, status, reference_code, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID        pgtype.UUID      `db:"user_id" json:"user_id"`
	PlanID        pgtype.UUID      `db:"plan_id" json:"plan_id"`
	Amount        int32            `db:"amount" json:"amount"`
	Currency      string           `db:"currency" json:"currency"`
	Method        string           `db:"method" json:"method"`
	Status        string           `db:"status" json:"status"`
	ReferenceCode string           `db:"reference_code" json:"reference_code"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

type CreatePaymentRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Insert a pending payment. Defaults (id, created_at, updated_at) are returned.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.PlanID,
		arg.Amount,
		arg.Currency,
		arg.Method,
		arg.Status,
		arg.ReferenceCode,
		arg.ExpiresAt,
	)
	var i CreatePaymentRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const findFirstActivePlanByPeriodCurrency = `-- name: FindFirstActivePlanByPeriodCurrency :one
SELECT id FROM plans
WHERE is_active = true AND billing_period = $1 AND currency = $2
ORDER BY created_at ASC
LIMIT 1
`

type FindFirstActivePlanByPeriodCurrencyParams struct {
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	Currency      *string                `db:"currency" json:"currency"`
}

// Ports plansService.findFirstActive({is_active, billing_period, currency},
// order created_at ASC). Returns the active plan id for that (period, currency).
func (q *Queries) FindFirstActivePlanByPeriodCurrency(ctx context.Context, arg FindFirstActivePlanByPeriodCurrencyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findFirstActivePlanByPeriodCurrency, arg.BillingPeriod, arg.Currency)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one

SELECT
  p.id, p.user_id, p.plan_id, p.amount, p.currency, p.method, p.status,
  p.provider_ref, p.reference_code, p.qr_data, p.notes,
  p.expires_at, p.completed_at, p.created_at, p.updated_at,
  pl.name AS plan_name
FROM payments p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.reference_code = $1
LIMIT 1
`

type GetPaymentByReferenceRow struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	UserID        pgtype.UUID      `db:"user_id" json:"user_id"`
	PlanID        pgtype.UUID      `db:"plan_id" json:"plan_id"`
	Amount        int32            `db:"amount" json:"amount"`
	Currency      string           `db:"currency" json:"currency"`
	Method        string           `db:"method" json:"method"`
	Status        string           `db:"status" json:"status"`
	ProviderRef   *string          `db:"provider_ref" json:"provider_ref"`
	ReferenceCode string           `db:"reference_code" json:"reference_code"`
	QrData        *string          `db:"qr_data" json:"qr_data"`
	Notes         *string          `db:"notes" json:"notes"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CompletedAt   pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	PlanName      *string          `db:"plan_name" json:"plan_name"`
}

// internal/shared/pg/queries_payment.sql
// Payment persistence (read paths for Phase 3a). Table public.payments is
// owned by the live NestJS-managed schema; mirror PaymentService read
// semantics exactly. Timestamps are "without time zone".
// getStatus(referenceCode): the pending/settled payment plus the plan name the
// controller surfaces as plan_name. LEFT JOIN so a payment whose plan row was
// deleted still returns (plan_name NULL), matching TypeORM relations:['plan']
// with a possibly-null relation.
func (q *Queries) GetPaymentByReference(ctx context.Context, referenceCode string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, referenceCode)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.ProviderRef,
		&i.ReferenceCode,
		&i.QrData,
		&i.Notes,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
	)
	return i, err
}

const getPaymentForWebhook = `-- name: GetPaymentForWebhook :one
SELECT pay.id, pay.user_id, pay.plan_id, pay.status, pay.currency, pay.method,
       p.billing_period
FROM payments pay
LEFT JOIN plans p ON p.id = pay.plan_id
WHERE pay.reference_code = $1
LIMIT 1
`

type GetPaymentForWebhookRow struct {
	ID            pgtype.UUID             `db:"id" json:"id"`
	UserID        pgtype.UUID             `db:"user_id" json:"user_id"`
	PlanID        pgtype.UUID             `db:"plan_id" json:"plan_id"`
	Status        string                  `db:"status" json:"status"`
	Currency      string                  `db:"currency" json:"currency"`
	Method        string                  `db:"method" json:"method"`
	BillingPeriod *PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
}

// completePayment / activate-subscription projection: the webhook resolves a
// payment by reference, then needs user/plan ids + current status + currency +
// the plan's billing_period (to re-resolve the active plan by variant). LEFT
// JOIN so billing_period is nullable in this row even though the column is NOT
// NULL on plans (payments always carry a plan in practice).
func (q *Queries) GetPaymentForWebhook(ctx context.Context, referenceCode string) (GetPaymentForWebhookRow, error) {
	row := q.db.QueryRow(ctx, getPaymentForWebhook, referenceCode)
	var i GetPaymentForWebhookRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.Currency,
		&i.Method,
		&i.BillingPeriod,
	)
	return i, err
}

const getPlanForCheckout = `-- name: GetPlanForCheckout :one
SELECT id, name, daily_limit, price_cents, currency, stripe_price_id, trial_days,
       billing_period, is_active, created_at, updated_at
FROM plans
WHERE id = $1
`

type GetPlanForCheckoutRow struct {
	ID            pgtype.UUID            `db:"id" json:"id"`
	Name          string                 `db:"name" json:"name"`
	DailyLimit    int32                  `db:"daily_limit" json:"daily_limit"`
	PriceCents    int32                  `db:"price_cents" json:"price_cents"`
	Currency      *string                `db:"currency" json:"currency"`
	StripePriceID *string                `db:"stripe_price_id" json:"stripe_price_id"`
	TrialDays     int32                  `db:"trial_days" json:"trial_days"`
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	IsActive      bool                   `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

// Full plan entity createCheckout needs: price_cents drives the free-plan guard +
// payment.amount, the strategy reads name/stripe_price_id/trial_days/billing_period,
// and the nested `payment.plan` response object serializes the WHOLE plan
// (daily_limit/is_active/created_at/updated_at included — Node attaches
// plansService.findById, the full entity). No row → pgx.ErrNoRows.
func (q *Queries) GetPlanForCheckout(ctx context.Context, id pgtype.UUID) (GetPlanForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, getPlanForCheckout, id)
	var i GetPlanForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DailyLimit,
		&i.PriceCents,
		&i.Currency,
		&i.StripePriceID,
		&i.TrialDays,
		&i.BillingPeriod,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEmailName = `-- name: GetUserEmailName :one
SELECT email, name FROM users WHERE id = $1
`

type GetUserEmailNameRow struct {
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"name"`
}

// activateSubscription's notify step: the webhook needs the paying user's email
// + display name to send the "subscription active" mail. name is NOT NULL
// (schema.sql), so sqlc generates a plain string (no pointer).
func (q *Queries) GetUserEmailName(ctx context.Context, id pgtype.UUID) (GetUserEmailNameRow, error) {
	row := q.db.QueryRow(ctx, getUserEmailName, id)
	var i GetUserEmailNameRow
	err := row.Scan(&i.Email, &i.Name)
	return i, err
}

const getUserForCheckout = `-- name: GetUserForCheckout :one
SELECT id, email, stripe_customer_id, lemonsqueezy_customer_id
FROM users
WHERE id = $1
`

type GetUserForCheckoutRow struct {
	ID                     pgtype.UUID `db:"id" json:"id"`
	Email                  string      `db:"email" json:"email"`
	StripeCustomerID       *string     `db:"stripe_customer_id" json:"stripe_customer_id"`
	LemonsqueezyCustomerID *string     `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
}

// User fields createCheckout / portal / cancel need. No row → pgx.ErrNoRows.
func (q *Queries) GetUserForCheckout(ctx context.Context, id pgtype.UUID) (GetUserForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, getUserForCheckout, id)
	var i GetUserForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.StripeCustomerID,
		&i.LemonsqueezyCustomerID,
	)
	return i, err
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT
  p.id, p.user_id, p.plan_id, p.amount, p.currency, p.method, p.status,
  p.provider_ref, p.reference_code, p.qr_data, p.notes,
  p.expires_at, p.completed_at, p.created_at, p.updated_at,
  pl.id AS plan_pk, pl.name AS plan_name, pl.daily_limit AS plan_daily_limit,
  pl.price_cents AS plan_price_cents, pl.currency AS plan_currency,
  pl.stripe_price_id AS plan_stripe_price_id, pl.trial_days AS plan_trial_days,
  pl.billing_period AS plan_billing_period, pl.is_active AS plan_is_active,
  pl.created_at AS plan_created_at, pl.updated_at AS plan_updated_at
FROM payments p
LEFT JOIN plans pl ON pl.id = p.plan_id
WHERE p.user_id = $1
ORDER BY p.created_at DESC
LIMIT 20
`

type ListPaymentsByUserRow struct {
	ID                pgtype.UUID             `db:"id" json:"id"`
	UserID            pgtype.UUID             `db:"user_id" json:"user_id"`
	PlanID            pgtype.UUID             `db:"plan_id" json:"plan_id"`
	Amount            int32                   `db:"amount" json:"amount"`
	Currency          string                  `db:"currency" json:"currency"`
	Method            string                  `db:"method" json:"method"`
	Status            string                  `db:"status" json:"status"`
	ProviderRef       *string                 `db:"provider_ref" json:"provider_ref"`
	ReferenceCode     string                  `db:"reference_code" json:"reference_code"`
	QrData            *string                 `db:"qr_data" json:"qr_data"`
	Notes             *string                 `db:"notes" json:"notes"`
	ExpiresAt         pgtype.Timestamp        `db:"expires_at" json:"expires_at"`
	CompletedAt       pgtype.Timestamp        `db:"completed_at" json:"completed_at"`
	CreatedAt         pgtype.Timestamp        `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp        `db:"updated_at" json:"updated_at"`
	PlanPk            pgtype.UUID             `db:"plan_pk" json:"plan_pk"`
	PlanName          *string                 `db:"plan_name" json:"plan_name"`
	PlanDailyLimit    *int32                  `db:"plan_daily_limit" json:"plan_daily_limit"`
	PlanPriceCents    *int32                  `db:"plan_price_cents" json:"plan_price_cents"`
	PlanCurrency      *string                 `db:"plan_currency" json:"plan_currency"`
	PlanStripePriceID *string                 `db:"plan_stripe_price_id" json:"plan_stripe_price_id"`
	PlanTrialDays     *int32                  `db:"plan_trial_days" json:"plan_trial_days"`
	PlanBillingPeriod *PlansBillingPeriodEnum `db:"plan_billing_period" json:"plan_billing_period"`
	PlanIsActive      *bool                   `db:"plan_is_active" json:"plan_is_active"`
	PlanCreatedAt     pgtype.Timestamp        `db:"plan_created_at" json:"plan_created_at"`
	PlanUpdatedAt     pgtype.Timestamp        `db:"plan_updated_at" json:"plan_updated_at"`
}

// findByUser(userId): the user's 20 most-recent payments, newest first, each
// with its plan (TypeORM relations:['plan'] order:{created_at:'DESC'} take:20).
func (q *Queries) ListPaymentsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPaymentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByUserRow{}
	for rows.Next() {
		var i ListPaymentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.Status,
			&i.ProviderRef,
			&i.ReferenceCode,
			&i.QrData,
			&i.Notes,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanPk,
			&i.PlanName,
			&i.PlanDailyLimit,
			&i.PlanPriceCents,
			&i.PlanCurrency,
			&i.PlanStripePriceID,
			&i.PlanTrialDays,
			&i.PlanBillingPeriod,
			&i.PlanIsActive,
			&i.PlanCreatedAt,
			&i.PlanUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentCompleted = `-- name: MarkPaymentCompleted :exec
UPDATE payments SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE reference_code = $1
`

func (q *Queries) MarkPaymentCompleted(ctx context.Context, referenceCode string) error {
	_, err := q.db.Exec(ctx, markPaymentCompleted, referenceCode)
	return err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :exec
UPDATE payments SET status = 'failed', notes = $2, updated_at = now() WHERE id = $1
`

type MarkPaymentFailedParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Notes *string     `db:"notes" json:"notes"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error {
	_, err := q.db.Exec(ctx, markPaymentFailed, arg.ID, arg.Notes)
	return err
}

const markPaymentFailedByRef = `-- name: MarkPaymentFailedByRef :exec
UPDATE payments SET status = 'failed', updated_at = NOW()
WHERE reference_code = $1
`

func (q *Queries) MarkPaymentFailedByRef(ctx context.Context, referenceCode string) error {
	_, err := q.db.Exec(ctx, markPaymentFailedByRef, referenceCode)
	return err
}

const paymentStats = `-- name: PaymentStats :one
SELECT
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE status = 'completed') AS completed,
  COUNT(*) FILTER (WHERE status = 'pending') AS pending,
  COALESCE(SUM(amount) FILTER (WHERE status = 'completed'), 0)::bigint AS revenue
FROM payments
`

type PaymentStatsRow struct {
	Total     int64 `db:"total" json:"total"`
	Completed int64 `db:"completed" json:"completed"`
	Pending   int64 `db:"pending" json:"pending"`
	Revenue   int64 `db:"revenue" json:"revenue"`
}

// getStats(): aggregate counts + completed revenue for GET /admin/payments/stats.
// Mirrors payment.service getStats — total/completed/pending counts plus
// COALESCE(SUM(amount),0) over completed rows. revenue is cast ::bigint so sqlc
// types it int64 (no numeric); the repo narrows to int (Node parseInt).
func (q *Queries) PaymentStats(ctx context.Context) (PaymentStatsRow, error) {
	row := q.db.QueryRow(ctx, paymentStats)
	var i PaymentStatsRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Pending,
		&i.Revenue,
	)
	return i, err
}

const setUserLemonSqueezyCustomerID = `-- name: SetUserLemonSqueezyCustomerID :exec
UPDATE users SET lemonsqueezy_customer_id = $2, updated_at = NOW() WHERE id = $1
`

type SetUserLemonSqueezyCustomerIDParams struct {
	ID                     pgtype.UUID `db:"id" json:"id"`
	LemonsqueezyCustomerID *string     `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
}

func (q *Queries) SetUserLemonSqueezyCustomerID(ctx context.Context, arg SetUserLemonSqueezyCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setUserLemonSqueezyCustomerID, arg.ID, arg.LemonsqueezyCustomerID)
	return err
}

const setUserStripeCustomerID = `-- name: SetUserStripeCustomerID :exec
UPDATE users SET stripe_customer_id = $2, updated_at = NOW() WHERE id = $1
`

type SetUserStripeCustomerIDParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	StripeCustomerID *string     `db:"stripe_customer_id" json:"stripe_customer_id"`
}

func (q *Queries) SetUserStripeCustomerID(ctx context.Context, arg SetUserStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setUserStripeCustomerID, arg.ID, arg.StripeCustomerID)
	return err
}

const updatePaymentPlan = `-- name: UpdatePaymentPlan :exec
UPDATE payments SET plan_id = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePaymentPlanParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	PlanID pgtype.UUID `db:"plan_id" json:"plan_id"`
}

func (q *Queries) UpdatePaymentPlan(ctx context.Context, arg UpdatePaymentPlanParams) error {
	_, err := q.db.Exec(ctx, updatePaymentPlan, arg.ID, arg.PlanID)
	return err
}

const updatePaymentQRData = `-- name: UpdatePaymentQRData :exec
UPDATE payments SET qr_data = $2, updated_at = now() WHERE id = $1
`

type UpdatePaymentQRDataParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	QrData *string     `db:"qr_data" json:"qr_data"`
}

func (q *Queries) UpdatePaymentQRData(ctx context.Context, arg UpdatePaymentQRDataParams) error {
	_, err := q.db.Exec(ctx, updatePaymentQRData, arg.ID, arg.QrData)
	return err
}
