// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeatures = `-- name: CountFeatures :one
SELECT COUNT(*) FROM bug_reports
WHERE kind = 'feature'
  AND is_public = true
  AND ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR target_platform = $2)
`

type CountFeaturesParams struct {
	Status         *string `db:"status" json:"status"`
	TargetPlatform *string `db:"target_platform" json:"target_platform"`
}

func (q *Queries) CountFeatures(ctx context.Context, arg CountFeaturesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFeatures, arg.Status, arg.TargetPlatform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotes = `-- name: CountVotes :one
SELECT COUNT(*) FROM feature_votes WHERE feature_id = $1
`

func (q *Queries) CountVotes(ctx context.Context, featureID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVotes, featureID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM feature_votes WHERE feature_id = $1 AND user_id = $2
`

type DeleteVoteParams struct {
	FeatureID pgtype.UUID `db:"feature_id" json:"feature_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.Exec(ctx, deleteVote, arg.FeatureID, arg.UserID)
	return err
}

const findFeature = `-- name: FindFeature :one
SELECT id FROM bug_reports WHERE id = $1 AND kind = 'feature'
`

func (q *Queries) FindFeature(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findFeature, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const findVote = `-- name: FindVote :one
SELECT id FROM feature_votes WHERE feature_id = $1 AND user_id = $2
`

type FindVoteParams struct {
	FeatureID pgtype.UUID `db:"feature_id" json:"feature_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) FindVote(ctx context.Context, arg FindVoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findVote, arg.FeatureID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertFeedback = `-- name: InsertFeedback :one

INSERT INTO bug_reports
  (kind, title, target_platform, vote_count, is_public, source, description,
   app_version, os_info, user_id, user_email, context, status)
VALUES ($1, $2, $3, 0, true, $4, $5, $6, $7, $8, $9, $10, 'new')
RETURNING id, display_no
`

type InsertFeedbackParams struct {
	Kind           string      `db:"kind" json:"kind"`
	Title          *string     `db:"title" json:"title"`
	TargetPlatform *string     `db:"target_platform" json:"target_platform"`
	Source         string      `db:"source" json:"source"`
	Description    string      `db:"description" json:"description"`
	AppVersion     *string     `db:"app_version" json:"app_version"`
	OsInfo         *string     `db:"os_info" json:"os_info"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	UserEmail      *string     `db:"user_email" json:"user_email"`
	Context        []byte      `db:"context" json:"context"`
}

type InsertFeedbackRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	DisplayNo int64       `db:"display_no" json:"display_no"`
}

// internal/shared/pg/queries_feedback.sql
// Public feedback board (POST /feedback, GET /feedback, POST /feedback/:id/vote).
// Shares the bug_reports table with bug-report ingest (kind='feature' vs 'bug')
// plus the feature_votes table (one vote per user per feature; vote_count is
// derived = COUNT(feature_votes)).
//
// The optional status / target_platform filters use the
// (@x::text IS NULL OR col = @x) idiom so CountFeatures and ListPublicFeatures
// share one WHERE clause; the use case passes NULL to skip a filter (mirrors
// Node only adding the key to its `where` object when the value passes its
// allow-list check).
func (q *Queries) InsertFeedback(ctx context.Context, arg InsertFeedbackParams) (InsertFeedbackRow, error) {
	row := q.db.QueryRow(ctx, insertFeedback,
		arg.Kind,
		arg.Title,
		arg.TargetPlatform,
		arg.Source,
		arg.Description,
		arg.AppVersion,
		arg.OsInfo,
		arg.UserID,
		arg.UserEmail,
		arg.Context,
	)
	var i InsertFeedbackRow
	err := row.Scan(&i.ID, &i.DisplayNo)
	return i, err
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO feature_votes (feature_id, user_id) VALUES ($1, $2)
`

type InsertVoteParams struct {
	FeatureID pgtype.UUID `db:"feature_id" json:"feature_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote, arg.FeatureID, arg.UserID)
	return err
}

const listPublicFeatures = `-- name: ListPublicFeatures :many
SELECT
  id, display_no, source, description, screenshot_path, screenshot_filename,
  app_version, os_info, user_id, user_email, context, status, kind, title,
  target_platform, vote_count, is_public, admin_notes, ai_fix_proposal,
  ai_fix_proposed_at, created_at, updated_at
FROM bug_reports
WHERE kind = 'feature'
  AND is_public = true
  AND ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR target_platform = $4)
ORDER BY vote_count DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicFeaturesParams struct {
	Limit          int32   `db:"limit" json:"limit"`
	Offset         int32   `db:"offset" json:"offset"`
	Status         *string `db:"status" json:"status"`
	TargetPlatform *string `db:"target_platform" json:"target_platform"`
}

type ListPublicFeaturesRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	DisplayNo          int64              `db:"display_no" json:"display_no"`
	Source             string             `db:"source" json:"source"`
	Description        string             `db:"description" json:"description"`
	ScreenshotPath     *string            `db:"screenshot_path" json:"screenshot_path"`
	ScreenshotFilename *string            `db:"screenshot_filename" json:"screenshot_filename"`
	AppVersion         *string            `db:"app_version" json:"app_version"`
	OsInfo             *string            `db:"os_info" json:"os_info"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	UserEmail          *string            `db:"user_email" json:"user_email"`
	Context            []byte             `db:"context" json:"context"`
	Status             *string            `db:"status" json:"status"`
	Kind               string             `db:"kind" json:"kind"`
	Title              *string            `db:"title" json:"title"`
	TargetPlatform     *string            `db:"target_platform" json:"target_platform"`
	VoteCount          int32              `db:"vote_count" json:"vote_count"`
	IsPublic           bool               `db:"is_public" json:"is_public"`
	AdminNotes         *string            `db:"admin_notes" json:"admin_notes"`
	AiFixProposal      *string            `db:"ai_fix_proposal" json:"ai_fix_proposal"`
	AiFixProposedAt    pgtype.Timestamptz `db:"ai_fix_proposed_at" json:"ai_fix_proposed_at"`
	CreatedAt          pgtype.Timestamp   `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListPublicFeatures(ctx context.Context, arg ListPublicFeaturesParams) ([]ListPublicFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listPublicFeatures,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.TargetPlatform,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicFeaturesRow{}
	for rows.Next() {
		var i ListPublicFeaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayNo,
			&i.Source,
			&i.Description,
			&i.ScreenshotPath,
			&i.ScreenshotFilename,
			&i.AppVersion,
			&i.OsInfo,
			&i.UserID,
			&i.UserEmail,
			&i.Context,
			&i.Status,
			&i.Kind,
			&i.Title,
			&i.TargetPlatform,
			&i.VoteCount,
			&i.IsPublic,
			&i.AdminNotes,
			&i.AiFixProposal,
			&i.AiFixProposedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureVoteCount = `-- name: UpdateFeatureVoteCount :exec
UPDATE bug_reports SET vote_count = $2 WHERE id = $1
`

type UpdateFeatureVoteCountParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	VoteCount int32       `db:"vote_count" json:"vote_count"`
}

func (q *Queries) UpdateFeatureVoteCount(ctx context.Context, arg UpdateFeatureVoteCountParams) error {
	_, err := q.db.Exec(ctx, updateFeatureVoteCount, arg.ID, arg.VoteCount)
	return err
}

const votedFeatureIDs = `-- name: VotedFeatureIDs :many
SELECT feature_id FROM feature_votes
WHERE feature_id = ANY($1::uuid[]) AND user_id = $2
`

type VotedFeatureIDsParams struct {
	FeatureIds []pgtype.UUID `db:"feature_ids" json:"feature_ids"`
	UserID     pgtype.UUID   `db:"user_id" json:"user_id"`
}

func (q *Queries) VotedFeatureIDs(ctx context.Context, arg VotedFeatureIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, votedFeatureIDs, arg.FeatureIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var feature_id pgtype.UUID
		if err := rows.Scan(&feature_id); err != nil {
			return nil, err
		}
		items = append(items, feature_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
