// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveSubsByUser = `-- name: CancelActiveSubsByUser :exec
UPDATE subscriptions SET status = 'cancelled'::subscriptions_status_enum, updated_at = now()
WHERE user_id = $1 AND status = 'active'::subscriptions_status_enum
`

func (q *Queries) CancelActiveSubsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelActiveSubsByUser, userID)
	return err
}

const cancelByStoreRef = `-- name: CancelByStoreRef :execrows
UPDATE subscriptions SET status = 'cancelled'::subscriptions_status_enum, updated_at = now()
WHERE store_type = $1 AND store_transaction_id = $2 AND status = 'active'::subscriptions_status_enum
`

type CancelByStoreRefParams struct {
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
}

func (q *Queries) CancelByStoreRef(ctx context.Context, arg CancelByStoreRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelByStoreRef, arg.StoreType, arg.StoreTransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveSubscriptions = `-- name: CountActiveSubscriptions :one
SELECT COUNT(*) FROM subscriptions WHERE status = 'active'::subscriptions_status_enum
`

// Mirrors subscriptionsService.countActive(): COUNT where status=active.
func (q *Queries) CountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChurnedInWindow = `-- name: CountChurnedInWindow :one
SELECT COUNT(*) FROM subscriptions
WHERE status IN ('cancelled'::subscriptions_status_enum, 'expired'::subscriptions_status_enum)
  AND updated_at >= $1 AND updated_at < $2
`

type CountChurnedInWindowParams struct {
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	UpdatedAt_2 pgtype.Timestamp `db:"updated_at_2" json:"updated_at_2"`
}

// Mirrors getMonthlyStats churned sub-query: subs with status cancelled or expired
// whose updated_at falls in [start, end). Node:
// .where('sub.status IN (:...statuses)', {statuses:['cancelled','expired']})
// .andWhere('sub.updated_at >= :start AND sub.updated_at < :end').getCount()
func (q *Queries) CountChurnedInWindow(ctx context.Context, arg CountChurnedInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countChurnedInWindow, arg.UpdatedAt, arg.UpdatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewSubsInWindow = `-- name: CountNewSubsInWindow :one
SELECT COUNT(*) FROM subscriptions
WHERE started_at >= $1 AND started_at < $2
`

type CountNewSubsInWindowParams struct {
	StartedAt   pgtype.Timestamp `db:"started_at" json:"started_at"`
	StartedAt_2 pgtype.Timestamp `db:"started_at_2" json:"started_at_2"`
}

// Mirrors getMonthlyStats new-subs sub-query: ALL subs started in [start, end).
// Node uses subsRepo.createQueryBuilder('sub').leftJoin('sub.plan','plan')
// .where('sub.started_at >= :start AND sub.started_at < :end').getCount()
// No status filter — matches Node exactly.
func (q *Queries) CountNewSubsInWindow(ctx context.Context, arg CountNewSubsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewSubsInWindow, arg.StartedAt, arg.StartedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageThisMonthAll = `-- name: CountUsageThisMonthAll :one
SELECT COUNT(*) FROM usage_logs WHERE created_at >= $1
`

// Global rewrite count since local first-of-month (Node usageService.countThisMonth()).
func (q *Queries) CountUsageThisMonthAll(ctx context.Context, createdAt pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageThisMonthAll, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageToday = `-- name: CountUsageToday :one
SELECT COUNT(*) FROM usage_logs
WHERE user_id = $1 AND created_at >= $2
`

type CountUsageTodayParams struct {
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

// Mirrors usageService.countTodayByUser: rows since local midnight.
// The caller passes the midnight boundary so timezone handling matches
// the Node process (new Date(); setHours(0,0,0,0)).
func (q *Queries) CountUsageToday(ctx context.Context, arg CountUsageTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageToday, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageTodayAll = `-- name: CountUsageTodayAll :one
SELECT COUNT(*) FROM usage_logs WHERE created_at >= $1
`

// Global rewrite count since local midnight (Node usageService.countToday()).
func (q *Queries) CountUsageTodayAll(ctx context.Context, createdAt pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageTodayAll, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFreeSubscription = `-- name: CreateFreeSubscription :exec
INSERT INTO subscriptions (user_id, plan_id, status, store_type, started_at, expires_at)
VALUES ($1, $2, 'active'::subscriptions_status_enum,
        'admin_granted'::subscriptions_store_type_enum, now(), null)
`

type CreateFreeSubscriptionParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	PlanID pgtype.UUID `db:"plan_id" json:"plan_id"`
}

func (q *Queries) CreateFreeSubscription(ctx context.Context, arg CreateFreeSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createFreeSubscription, arg.UserID, arg.PlanID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, password_hash, name, auth_provider, avatar_url, email_verified,
  email_verification_code, email_verification_expires,
  google_id, facebook_id, tiktok_id, apple_id
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, email, name, avatar_url, email_verified
`

type CreateUserParams struct {
	Email                    string                `db:"email" json:"email"`
	PasswordHash             *string               `db:"password_hash" json:"password_hash"`
	Name                     string                `db:"name" json:"name"`
	AuthProvider             UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	AvatarUrl                *string               `db:"avatar_url" json:"avatar_url"`
	EmailVerified            bool                  `db:"email_verified" json:"email_verified"`
	EmailVerificationCode    *string               `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz    `db:"email_verification_expires" json:"email_verification_expires"`
	GoogleID                 *string               `db:"google_id" json:"google_id"`
	FacebookID               *string               `db:"facebook_id" json:"facebook_id"`
	TiktokID                 *string               `db:"tiktok_id" json:"tiktok_id"`
	AppleID                  *string               `db:"apple_id" json:"apple_id"`
}

type CreateUserRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	Email         string      `db:"email" json:"email"`
	Name          string      `db:"name" json:"name"`
	AvatarUrl     *string     `db:"avatar_url" json:"avatar_url"`
	EmailVerified bool        `db:"email_verified" json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AuthProvider,
		arg.AvatarUrl,
		arg.EmailVerified,
		arg.EmailVerificationCode,
		arg.EmailVerificationExpires,
		arg.GoogleID,
		arg.FacebookID,
		arg.TiktokID,
		arg.AppleID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const expireByStoreRef = `-- name: ExpireByStoreRef :execrows
UPDATE subscriptions SET status = 'expired'::subscriptions_status_enum, expires_at = now(), updated_at = now()
WHERE store_type = $1 AND store_transaction_id = $2
`

type ExpireByStoreRefParams struct {
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
}

func (q *Queries) ExpireByStoreRef(ctx context.Context, arg ExpireByStoreRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireByStoreRef, arg.StoreType, arg.StoreTransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireLapsedSubs = `-- name: ExpireLapsedSubs :many
UPDATE subscriptions s
SET status = 'expired'::subscriptions_status_enum, updated_at = now()
FROM users u
WHERE u.id = s.user_id
  AND s.status IN ('active'::subscriptions_status_enum, 'cancelled'::subscriptions_status_enum)
  AND s.expires_at < $1
RETURNING s.user_id, u.email, s.expires_at
`

type ExpireLapsedSubsRow struct {
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Email     string           `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

// Cron pass 2: flip active|cancelled subs past expiry to expired, returning
// the affected rows so the caller can email each. expires_at left untouched.
func (q *Queries) ExpireLapsedSubs(ctx context.Context, expiresAt pgtype.Timestamp) ([]ExpireLapsedSubsRow, error) {
	rows, err := q.db.Query(ctx, expireLapsedSubs, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireLapsedSubsRow{}
	for rows.Next() {
		var i ExpireLapsedSubsRow
		if err := rows.Scan(&i.UserID, &i.Email, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const extendByStoreRef = `-- name: ExtendByStoreRef :execrows
UPDATE subscriptions SET expires_at = $3, updated_at = now()
WHERE store_type = $1 AND store_transaction_id = $2 AND status = 'active'::subscriptions_status_enum
`

type ExtendByStoreRefParams struct {
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
	ExpiresAt          pgtype.Timestamp           `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ExtendByStoreRef(ctx context.Context, arg ExtendByStoreRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendByStoreRef, arg.StoreType, arg.StoreTransactionID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findByStoreRef = `-- name: FindByStoreRef :one
SELECT sub.user_id, u.email AS user_email, u.name AS user_name, p.name AS plan_name
FROM subscriptions sub
JOIN users u ON u.id = sub.user_id
JOIN plans p ON p.id = sub.plan_id
WHERE sub.store_type = $1 AND sub.store_transaction_id = $2
LIMIT 1
`

type FindByStoreRefParams struct {
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
}

type FindByStoreRefRow struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	UserEmail string      `db:"user_email" json:"user_email"`
	UserName  string      `db:"user_name" json:"user_name"`
	PlanName  string      `db:"plan_name" json:"plan_name"`
}

func (q *Queries) FindByStoreRef(ctx context.Context, arg FindByStoreRefParams) (FindByStoreRefRow, error) {
	row := q.db.QueryRow(ctx, findByStoreRef, arg.StoreType, arg.StoreTransactionID)
	var i FindByStoreRefRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.PlanName,
	)
	return i, err
}

const findFreePlan = `-- name: FindFreePlan :one
SELECT id, name, daily_limit FROM plans
WHERE billing_period = 'none'::plans_billing_period_enum AND is_active = true
LIMIT 1
`

type FindFreePlanRow struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	DailyLimit int32       `db:"daily_limit" json:"daily_limit"`
}

func (q *Queries) FindFreePlan(ctx context.Context) (FindFreePlanRow, error) {
	row := q.db.QueryRow(ctx, findFreePlan)
	var i FindFreePlanRow
	err := row.Scan(&i.ID, &i.Name, &i.DailyLimit)
	return i, err
}

const findUserByAppleId = `-- name: FindUserByAppleId :one
SELECT id, email, password_hash, name, is_active, role, auth_provider,
       email_verified, lemonsqueezy_customer_id, avatar_url
FROM users WHERE apple_id = $1 LIMIT 1
`

type FindUserByAppleIdRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	AvatarUrl              *string               `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) FindUserByAppleId(ctx context.Context, appleID *string) (FindUserByAppleIdRow, error) {
	row := q.db.QueryRow(ctx, findUserByAppleId, appleID)
	var i FindUserByAppleIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
		&i.AvatarUrl,
	)
	return i, err
}

const findUserByFacebookId = `-- name: FindUserByFacebookId :one
SELECT id, email, password_hash, name, is_active, role, auth_provider,
       email_verified, lemonsqueezy_customer_id, avatar_url
FROM users WHERE facebook_id = $1 LIMIT 1
`

type FindUserByFacebookIdRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	AvatarUrl              *string               `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) FindUserByFacebookId(ctx context.Context, facebookID *string) (FindUserByFacebookIdRow, error) {
	row := q.db.QueryRow(ctx, findUserByFacebookId, facebookID)
	var i FindUserByFacebookIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
		&i.AvatarUrl,
	)
	return i, err
}

const findUserByGoogleId = `-- name: FindUserByGoogleId :one
SELECT id, email, password_hash, name, is_active, role, auth_provider,
       email_verified, lemonsqueezy_customer_id, avatar_url
FROM users WHERE google_id = $1 LIMIT 1
`

type FindUserByGoogleIdRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	AvatarUrl              *string               `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) FindUserByGoogleId(ctx context.Context, googleID *string) (FindUserByGoogleIdRow, error) {
	row := q.db.QueryRow(ctx, findUserByGoogleId, googleID)
	var i FindUserByGoogleIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
		&i.AvatarUrl,
	)
	return i, err
}

const findUserByTiktokId = `-- name: FindUserByTiktokId :one
SELECT id, email, password_hash, name, is_active, role, auth_provider,
       email_verified, lemonsqueezy_customer_id, avatar_url
FROM users WHERE tiktok_id = $1 LIMIT 1
`

type FindUserByTiktokIdRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
	AvatarUrl              *string               `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) FindUserByTiktokId(ctx context.Context, tiktokID *string) (FindUserByTiktokIdRow, error) {
	row := q.db.QueryRow(ctx, findUserByTiktokId, tiktokID)
	var i FindUserByTiktokIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
		&i.AvatarUrl,
	)
	return i, err
}

const getActiveSubWithPlan = `-- name: GetActiveSubWithPlan :one
SELECT s.status, s.expires_at,
       p.name AS plan_name, p.daily_limit, p.billing_period
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1 AND s.status = 'active'::subscriptions_status_enum
ORDER BY s.created_at DESC
LIMIT 1
`

type GetActiveSubWithPlanRow struct {
	Status        SubscriptionsStatusEnum `db:"status" json:"status"`
	ExpiresAt     pgtype.Timestamp        `db:"expires_at" json:"expires_at"`
	PlanName      string                  `db:"plan_name" json:"plan_name"`
	DailyLimit    int32                   `db:"daily_limit" json:"daily_limit"`
	BillingPeriod PlansBillingPeriodEnum  `db:"billing_period" json:"billing_period"`
}

// GET /subscription: newest active sub + plan fields incl billing_period.
// Distinct from GetActiveSubscriptionByUserID (which omits billing_period
// and is pinned for /auth/account).
func (q *Queries) GetActiveSubWithPlan(ctx context.Context, userID pgtype.UUID) (GetActiveSubWithPlanRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubWithPlan, userID)
	var i GetActiveSubWithPlanRow
	err := row.Scan(
		&i.Status,
		&i.ExpiresAt,
		&i.PlanName,
		&i.DailyLimit,
		&i.BillingPeriod,
	)
	return i, err
}

const getActiveSubscriptionByUserID = `-- name: GetActiveSubscriptionByUserID :one
SELECT s.status, s.store_type, s.started_at, s.expires_at, s.store_transaction_id,
       p.name AS plan_name, p.daily_limit
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1 AND s.status = 'active'::subscriptions_status_enum
ORDER BY s.created_at DESC
LIMIT 1
`

type GetActiveSubscriptionByUserIDRow struct {
	Status             SubscriptionsStatusEnum    `db:"status" json:"status"`
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StartedAt          pgtype.Timestamp           `db:"started_at" json:"started_at"`
	ExpiresAt          pgtype.Timestamp           `db:"expires_at" json:"expires_at"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
	PlanName           string                     `db:"plan_name" json:"plan_name"`
	DailyLimit         int32                      `db:"daily_limit" json:"daily_limit"`
}

// Mirrors subscriptionsService.findActiveByUserId: newest ACTIVE
// subscription for the user, joined to its plan. ORDER BY created_at
// DESC + LIMIT 1 reproduces TypeORM order:{created_at:'DESC'} findOne.
func (q *Queries) GetActiveSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetActiveSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByUserID, userID)
	var i GetActiveSubscriptionByUserIDRow
	err := row.Scan(
		&i.Status,
		&i.StoreType,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.StoreTransactionID,
		&i.PlanName,
		&i.DailyLimit,
	)
	return i, err
}

const getAuthTokenSettings = `-- name: GetAuthTokenSettings :one
SELECT token_expiry_minutes, refresh_token_expiry_days
FROM app_settings
LIMIT 1
`

type GetAuthTokenSettingsRow struct {
	TokenExpiryMinutes     int32 `db:"token_expiry_minutes" json:"token_expiry_minutes"`
	RefreshTokenExpiryDays int32 `db:"refresh_token_expiry_days" json:"refresh_token_expiry_days"`
}

// The single app_settings row's token lifetimes. No row → caller uses
// defaults (15 / 90), matching Node's `?? 15` / `?? 90`.
func (q *Queries) GetAuthTokenSettings(ctx context.Context) (GetAuthTokenSettingsRow, error) {
	row := q.db.QueryRow(ctx, getAuthTokenSettings)
	var i GetAuthTokenSettingsRow
	err := row.Scan(&i.TokenExpiryMinutes, &i.RefreshTokenExpiryDays)
	return i, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one

SELECT id, email, password_hash, name, is_active, role,
       auth_provider, email_verified, lemonsqueezy_customer_id
FROM users
WHERE email = $1
LIMIT 1
`

type GetAuthUserByEmailRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
}

// Phase 1a auth queries. Read the live NestJS-owned schema as-is.
// Full projection for /auth/login. password_hash is nullable
// (social-only accounts have none). No email normalization — Node's
// login passes the email through unchanged.
func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (GetAuthUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i GetAuthUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, email, password_hash, name, is_active, role,
       auth_provider, email_verified, lemonsqueezy_customer_id
FROM users
WHERE id = $1
LIMIT 1
`

type GetAuthUserByIDRow struct {
	ID                     pgtype.UUID           `db:"id" json:"id"`
	Email                  string                `db:"email" json:"email"`
	PasswordHash           *string               `db:"password_hash" json:"password_hash"`
	Name                   string                `db:"name" json:"name"`
	IsActive               bool                  `db:"is_active" json:"is_active"`
	Role                   UsersRoleEnum         `db:"role" json:"role"`
	AuthProvider           UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	EmailVerified          bool                  `db:"email_verified" json:"email_verified"`
	LemonsqueezyCustomerID *string               `db:"lemonsqueezy_customer_id" json:"lemonsqueezy_customer_id"`
}

// Same projection keyed by id — used by refresh, change-password, account.
func (q *Queries) GetAuthUserByID(ctx context.Context, id pgtype.UUID) (GetAuthUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i GetAuthUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.IsActive,
		&i.Role,
		&i.AuthProvider,
		&i.EmailVerified,
		&i.LemonsqueezyCustomerID,
	)
	return i, err
}

const getEmailSettings = `-- name: GetEmailSettings :one
SELECT resend_api_key, email_from FROM app_settings LIMIT 1
`

type GetEmailSettingsRow struct {
	ResendApiKey string `db:"resend_api_key" json:"resend_api_key"`
	EmailFrom    string `db:"email_from" json:"email_from"`
}

// app_settings creds: both columns are NOT NULL (default ”).
func (q *Queries) GetEmailSettings(ctx context.Context) (GetEmailSettingsRow, error) {
	row := q.db.QueryRow(ctx, getEmailSettings)
	var i GetEmailSettingsRow
	err := row.Scan(&i.ResendApiKey, &i.EmailFrom)
	return i, err
}

const getEmailTemplateByKey = `-- name: GetEmailTemplateByKey :one
SELECT subject, html FROM email_templates WHERE template_key = $1 LIMIT 1
`

type GetEmailTemplateByKeyRow struct {
	Subject string `db:"subject" json:"subject"`
	Html    string `db:"html" json:"html"`
}

// DB template override. PK column is template_key (not key).
func (q *Queries) GetEmailTemplateByKey(ctx context.Context, templateKey string) (GetEmailTemplateByKeyRow, error) {
	row := q.db.QueryRow(ctx, getEmailTemplateByKey, templateKey)
	var i GetEmailTemplateByKeyRow
	err := row.Scan(&i.Subject, &i.Html)
	return i, err
}

const getLastExpiredAt = `-- name: GetLastExpiredAt :one
SELECT updated_at FROM subscriptions
WHERE user_id = $1 AND status = 'expired'::subscriptions_status_enum
ORDER BY updated_at DESC
LIMIT 1
`

// updated_at of the user's most-recently expired subscription (free-tier
// just_expired banner). No row → caller treats as nil.
func (q *Queries) GetLastExpiredAt(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getLastExpiredAt, userID)
	var updated_at pgtype.Timestamp
	err := row.Scan(&updated_at)
	return updated_at, err
}

const getUserAuthState = `-- name: GetUserAuthState :one
SELECT id, email, name, password_hash, auth_provider, is_active,
       email_verified, email_verification_code, email_verification_expires,
       password_reset_code, password_reset_expires, password_reset_attempts
FROM users WHERE email = $1 LIMIT 1
`

type GetUserAuthStateRow struct {
	ID                       pgtype.UUID           `db:"id" json:"id"`
	Email                    string                `db:"email" json:"email"`
	Name                     string                `db:"name" json:"name"`
	PasswordHash             *string               `db:"password_hash" json:"password_hash"`
	AuthProvider             UsersAuthProviderEnum `db:"auth_provider" json:"auth_provider"`
	IsActive                 bool                  `db:"is_active" json:"is_active"`
	EmailVerified            bool                  `db:"email_verified" json:"email_verified"`
	EmailVerificationCode    *string               `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz    `db:"email_verification_expires" json:"email_verification_expires"`
	PasswordResetCode        *string               `db:"password_reset_code" json:"password_reset_code"`
	PasswordResetExpires     pgtype.Timestamptz    `db:"password_reset_expires" json:"password_reset_expires"`
	PasswordResetAttempts    int32                 `db:"password_reset_attempts" json:"password_reset_attempts"`
}

func (q *Queries) GetUserAuthState(ctx context.Context, email string) (GetUserAuthStateRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthState, email)
	var i GetUserAuthStateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.IsActive,
		&i.EmailVerified,
		&i.EmailVerificationCode,
		&i.EmailVerificationExpires,
		&i.PasswordResetCode,
		&i.PasswordResetExpires,
		&i.PasswordResetAttempts,
	)
	return i, err
}

const insertEmailLog = `-- name: InsertEmailLog :exec
INSERT INTO email_logs (to_email, email_type, subject, status, provider_id, error)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEmailLogParams struct {
	ToEmail    string  `db:"to_email" json:"to_email"`
	EmailType  string  `db:"email_type" json:"email_type"`
	Subject    string  `db:"subject" json:"subject"`
	Status     string  `db:"status" json:"status"`
	ProviderID *string `db:"provider_id" json:"provider_id"`
	Error      *string `db:"error" json:"error"`
}

// Audit row for every deliver attempt (suppressed/skipped/sent/failed).
func (q *Queries) InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) error {
	_, err := q.db.Exec(ctx, insertEmailLog,
		arg.ToEmail,
		arg.EmailType,
		arg.Subject,
		arg.Status,
		arg.ProviderID,
		arg.Error,
	)
	return err
}

const insertGrantedSubscription = `-- name: InsertGrantedSubscription :exec
INSERT INTO subscriptions (user_id, plan_id, status, store_type, started_at, expires_at)
VALUES ($1, $2, 'active'::subscriptions_status_enum, $3, now(), $4)
`

type InsertGrantedSubscriptionParams struct {
	UserID    pgtype.UUID                `db:"user_id" json:"user_id"`
	PlanID    pgtype.UUID                `db:"plan_id" json:"plan_id"`
	StoreType SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	ExpiresAt pgtype.Timestamp           `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertGrantedSubscription(ctx context.Context, arg InsertGrantedSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertGrantedSubscription,
		arg.UserID,
		arg.PlanID,
		arg.StoreType,
		arg.ExpiresAt,
	)
	return err
}

const isEmailSuppressed = `-- name: IsEmailSuppressed :one
SELECT COUNT(*) > 0 FROM email_suppressions WHERE email = $1
`

// Lowercased-email suppression check (bounce/complaint list).
func (q *Queries) IsEmailSuppressed(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailSuppressed, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const linkSocialApple = `-- name: LinkSocialApple :exec
UPDATE users SET apple_id = $2, avatar_url = $3, email_verified = true,
  updated_at = now() WHERE id = $1
`

type LinkSocialAppleParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	AppleID   *string     `db:"apple_id" json:"apple_id"`
	AvatarUrl *string     `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) LinkSocialApple(ctx context.Context, arg LinkSocialAppleParams) error {
	_, err := q.db.Exec(ctx, linkSocialApple, arg.ID, arg.AppleID, arg.AvatarUrl)
	return err
}

const linkSocialFacebook = `-- name: LinkSocialFacebook :exec
UPDATE users SET facebook_id = $2, avatar_url = $3, email_verified = true,
  updated_at = now() WHERE id = $1
`

type LinkSocialFacebookParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	FacebookID *string     `db:"facebook_id" json:"facebook_id"`
	AvatarUrl  *string     `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) LinkSocialFacebook(ctx context.Context, arg LinkSocialFacebookParams) error {
	_, err := q.db.Exec(ctx, linkSocialFacebook, arg.ID, arg.FacebookID, arg.AvatarUrl)
	return err
}

const linkSocialGoogle = `-- name: LinkSocialGoogle :exec
UPDATE users SET google_id = $2, avatar_url = $3, email_verified = true,
  updated_at = now() WHERE id = $1
`

type LinkSocialGoogleParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	GoogleID  *string     `db:"google_id" json:"google_id"`
	AvatarUrl *string     `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) LinkSocialGoogle(ctx context.Context, arg LinkSocialGoogleParams) error {
	_, err := q.db.Exec(ctx, linkSocialGoogle, arg.ID, arg.GoogleID, arg.AvatarUrl)
	return err
}

const linkSocialTiktok = `-- name: LinkSocialTiktok :exec
UPDATE users SET tiktok_id = $2, avatar_url = $3, email_verified = true,
  updated_at = now() WHERE id = $1
`

type LinkSocialTiktokParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	TiktokID  *string     `db:"tiktok_id" json:"tiktok_id"`
	AvatarUrl *string     `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) LinkSocialTiktok(ctx context.Context, arg LinkSocialTiktokParams) error {
	_, err := q.db.Exec(ctx, linkSocialTiktok, arg.ID, arg.TiktokID, arg.AvatarUrl)
	return err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, name, daily_limit, price_cents, currency, stripe_price_id,
       trial_days, billing_period, is_active, created_at, updated_at
FROM plans
WHERE is_active = true
ORDER BY price_cents ASC
`

type ListActivePlansRow struct {
	ID            pgtype.UUID            `db:"id" json:"id"`
	Name          string                 `db:"name" json:"name"`
	DailyLimit    int32                  `db:"daily_limit" json:"daily_limit"`
	PriceCents    int32                  `db:"price_cents" json:"price_cents"`
	Currency      *string                `db:"currency" json:"currency"`
	StripePriceID *string                `db:"stripe_price_id" json:"stripe_price_id"`
	TrialDays     int32                  `db:"trial_days" json:"trial_days"`
	BillingPeriod PlansBillingPeriodEnum `db:"billing_period" json:"billing_period"`
	IsActive      bool                   `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamp       `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp       `db:"updated_at" json:"updated_at"`
}

// Mirrors plansService.findAll(): every active plan, cheapest first.
// No tiebreaker beyond price_cents (matches TypeORM order:{price_cents:'ASC'}).
func (q *Queries) ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlansRow{}
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DailyLimit,
			&i.PriceCents,
			&i.Currency,
			&i.StripePriceID,
			&i.TrialDays,
			&i.BillingPeriod,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const plansBreakdown = `-- name: PlansBreakdown :many
SELECT p.name AS plan_name, p.price_cents AS price_cents, COUNT(*) AS active_count
FROM subscriptions s
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.status = 'active'::subscriptions_status_enum
GROUP BY p.name, p.price_cents
`

type PlansBreakdownRow struct {
	PlanName    *string `db:"plan_name" json:"plan_name"`
	PriceCents  *int32  `db:"price_cents" json:"price_cents"`
	ActiveCount int64   `db:"active_count" json:"active_count"`
}

// Mirrors subscriptionsService.getPlansBreakdown(): active subs grouped by plan.
// LEFT JOIN so subs with no plan row (data-quality gap) still appear.
func (q *Queries) PlansBreakdown(ctx context.Context) ([]PlansBreakdownRow, error) {
	rows, err := q.db.Query(ctx, plansBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlansBreakdownRow{}
	for rows.Next() {
		var i PlansBreakdownRow
		if err := rows.Scan(&i.PlanName, &i.PriceCents, &i.ActiveCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPasswordHash = `-- name: ResetPasswordHash :exec
UPDATE users SET password_hash = $2, password_reset_code = null,
  password_reset_expires = null, password_reset_attempts = 0,
  updated_at = now() WHERE id = $1
`

type ResetPasswordHashParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
}

func (q *Queries) ResetPasswordHash(ctx context.Context, arg ResetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, resetPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const setEmailVerificationCode = `-- name: SetEmailVerificationCode :exec
UPDATE users SET email_verification_code = $2, email_verification_expires = $3,
  updated_at = now() WHERE id = $1
`

type SetEmailVerificationCodeParams struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	EmailVerificationCode    *string            `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz `db:"email_verification_expires" json:"email_verification_expires"`
}

func (q *Queries) SetEmailVerificationCode(ctx context.Context, arg SetEmailVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, setEmailVerificationCode, arg.ID, arg.EmailVerificationCode, arg.EmailVerificationExpires)
	return err
}

const setPasswordResetAttempts = `-- name: SetPasswordResetAttempts :exec
UPDATE users SET password_reset_attempts = $2, updated_at = now() WHERE id = $1
`

type SetPasswordResetAttemptsParams struct {
	ID                    pgtype.UUID `db:"id" json:"id"`
	PasswordResetAttempts int32       `db:"password_reset_attempts" json:"password_reset_attempts"`
}

func (q *Queries) SetPasswordResetAttempts(ctx context.Context, arg SetPasswordResetAttemptsParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetAttempts, arg.ID, arg.PasswordResetAttempts)
	return err
}

const setPasswordResetCode = `-- name: SetPasswordResetCode :exec
UPDATE users SET password_reset_code = $2, password_reset_expires = $3,
  password_reset_attempts = $4, updated_at = now() WHERE id = $1
`

type SetPasswordResetCodeParams struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	PasswordResetCode     *string            `db:"password_reset_code" json:"password_reset_code"`
	PasswordResetExpires  pgtype.Timestamptz `db:"password_reset_expires" json:"password_reset_expires"`
	PasswordResetAttempts int32              `db:"password_reset_attempts" json:"password_reset_attempts"`
}

func (q *Queries) SetPasswordResetCode(ctx context.Context, arg SetPasswordResetCodeParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetCode,
		arg.ID,
		arg.PasswordResetCode,
		arg.PasswordResetExpires,
		arg.PasswordResetAttempts,
	)
	return err
}

const stampStoreRefByReference = `-- name: StampStoreRefByReference :execrows
UPDATE subscriptions SET store_type = $2, store_transaction_id = $3, updated_at = now()
WHERE id = (
  SELECT sub.id FROM subscriptions sub
  INNER JOIN payments pay ON pay.user_id = sub.user_id AND pay.reference_code = $1
  WHERE sub.status = 'active'::subscriptions_status_enum
  ORDER BY sub.created_at DESC
  LIMIT 1
)
`

type StampStoreRefByReferenceParams struct {
	ReferenceCode      string                     `db:"reference_code" json:"reference_code"`
	StoreType          SubscriptionsStoreTypeEnum `db:"store_type" json:"store_type"`
	StoreTransactionID *string                    `db:"store_transaction_id" json:"store_transaction_id"`
}

func (q *Queries) StampStoreRefByReference(ctx context.Context, arg StampStoreRefByReferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, stampStoreRefByReference, arg.ReferenceCode, arg.StoreType, arg.StoreTransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subsDueForRenewal = `-- name: SubsDueForRenewal :many
SELECT s.user_id, u.email, s.expires_at, p.name AS plan_name
FROM subscriptions s
JOIN users u ON u.id = s.user_id
JOIN plans p ON p.id = s.plan_id
WHERE s.status = 'active'::subscriptions_status_enum
  AND s.expires_at >= $1 AND s.expires_at <= $2
`

type SubsDueForRenewalParams struct {
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	ExpiresAt_2 pgtype.Timestamp `db:"expires_at_2" json:"expires_at_2"`
}

type SubsDueForRenewalRow struct {
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Email     string           `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	PlanName  string           `db:"plan_name" json:"plan_name"`
}

// Cron pass 1: active subs whose expiry falls in the reminder window.
// Bounds passed by caller (now+2.5d, now+3.5d) to keep tz in the Go process.
func (q *Queries) SubsDueForRenewal(ctx context.Context, arg SubsDueForRenewalParams) ([]SubsDueForRenewalRow, error) {
	rows, err := q.db.Query(ctx, subsDueForRenewal, arg.ExpiresAt, arg.ExpiresAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubsDueForRenewalRow{}
	for rows.Next() {
		var i SubsDueForRenewalRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.ExpiresAt,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRevenueInWindow = `-- name: SumRevenueInWindow :one
SELECT COALESCE(SUM(p.price_cents), 0)::bigint AS total
FROM subscriptions s
LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.started_at >= $1 AND s.started_at < $2
`

type SumRevenueInWindowParams struct {
	StartedAt   pgtype.Timestamp `db:"started_at" json:"started_at"`
	StartedAt_2 pgtype.Timestamp `db:"started_at_2" json:"started_at_2"`
}

// Mirrors getMonthlyStats revenue sub-query: SUM(plan.price_cents) for subs
// started in [start, end). Node: COALESCE(SUM(plan.price_cents),0) via leftJoin.
// No status filter — matches Node exactly. Cast to bigint for pgx scan.
func (q *Queries) SumRevenueInWindow(ctx context.Context, arg SumRevenueInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumRevenueInWindow, arg.StartedAt, arg.StartedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash *string     `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserVerification = `-- name: UpdateUserVerification :exec
UPDATE users SET email_verified = $2, email_verification_code = $3,
  email_verification_expires = $4, updated_at = now() WHERE id = $1
`

type UpdateUserVerificationParams struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	EmailVerified            bool               `db:"email_verified" json:"email_verified"`
	EmailVerificationCode    *string            `db:"email_verification_code" json:"email_verification_code"`
	EmailVerificationExpires pgtype.Timestamptz `db:"email_verification_expires" json:"email_verification_expires"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) error {
	_, err := q.db.Exec(ctx, updateUserVerification,
		arg.ID,
		arg.EmailVerified,
		arg.EmailVerificationCode,
		arg.EmailVerificationExpires,
	)
	return err
}
