// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_rewritelog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingRewriteLogs = `-- name: CountPendingRewriteLogs :one
SELECT COUNT(*) FROM rewrite_logs WHERE quality = 'pending'
`

// Count twin of ListPendingRewriteLogs (no LIMIT/OFFSET).
func (q *Queries) CountPendingRewriteLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRewriteLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRewriteLogs = `-- name: CountRewriteLogs :one

SELECT COUNT(*) FROM rewrite_logs
`

// internal/shared/pg/queries_rewritelog.sql
// Admin training-data endpoints (GET /admin/training-data/stats,
// GET /admin/training-data, PATCH /admin/training-data/:id,
// GET /admin/training-data/export).
// Mirrors RewriteLogService (backend/src/rewrite/rewrite-log.service.ts).
func (q *Queries) CountRewriteLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRewriteLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRewriteLogsByQuality = `-- name: CountRewriteLogsByQuality :many
SELECT quality, COUNT(*) AS n FROM rewrite_logs GROUP BY quality
`

type CountRewriteLogsByQualityRow struct {
	Quality string `db:"quality" json:"quality"`
	N       int64  `db:"n" json:"n"`
}

// One row per distinct quality value — caller maps to (pending, approved, rejected).
func (q *Queries) CountRewriteLogsByQuality(ctx context.Context) ([]CountRewriteLogsByQualityRow, error) {
	rows, err := q.db.Query(ctx, countRewriteLogsByQuality)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRewriteLogsByQualityRow{}
	for rows.Next() {
		var i CountRewriteLogsByQualityRow
		if err := rows.Scan(&i.Quality, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedRewriteLogsAsc = `-- name: ListApprovedRewriteLogsAsc :many
SELECT id, tone, input_text, output_text, model, provider_type, response_time_ms, quality, created_at
FROM rewrite_logs
WHERE quality = 'approved'
ORDER BY created_at ASC
`

// exportApproved / exportAll: quality='approved', oldest first.
// Node: find({ where: { quality: 'approved' }, order: { created_at: 'ASC' } })
func (q *Queries) ListApprovedRewriteLogsAsc(ctx context.Context) ([]RewriteLog, error) {
	rows, err := q.db.Query(ctx, listApprovedRewriteLogsAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewriteLog{}
	for rows.Next() {
		var i RewriteLog
		if err := rows.Scan(
			&i.ID,
			&i.Tone,
			&i.InputText,
			&i.OutputText,
			&i.Model,
			&i.ProviderType,
			&i.ResponseTimeMs,
			&i.Quality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRewriteLogs = `-- name: ListPendingRewriteLogs :many
SELECT id, tone, input_text, output_text, model, provider_type, response_time_ms, quality, created_at
FROM rewrite_logs
WHERE quality = 'pending'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingRewriteLogsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// findPending: quality='pending', newest first, with LIMIT/OFFSET pagination.
// Node: findAndCount({ where: { quality: 'pending' }, order: { created_at: 'DESC' },
//
//	skip: (page-1)*limit, take: limit })
func (q *Queries) ListPendingRewriteLogs(ctx context.Context, arg ListPendingRewriteLogsParams) ([]RewriteLog, error) {
	rows, err := q.db.Query(ctx, listPendingRewriteLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewriteLog{}
	for rows.Next() {
		var i RewriteLog
		if err := rows.Scan(
			&i.ID,
			&i.Tone,
			&i.InputText,
			&i.OutputText,
			&i.Model,
			&i.ProviderType,
			&i.ResponseTimeMs,
			&i.Quality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRewriteLogQuality = `-- name: UpdateRewriteLogQuality :exec
UPDATE rewrite_logs SET quality = $2 WHERE id = $1
`

type UpdateRewriteLogQualityParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Quality string      `db:"quality" json:"quality"`
}

// updateQuality(id, quality): update the quality field for one row.
// Node: rewriteLogRepo.update(id, { quality }) — TypeORM silently no-ops on
// a missing UUID (0 rows affected, no error). Go mirrors: valid UUID → run UPDATE
// (0-row no-op is fine); invalid UUID → caller returns nil without touching DB.
func (q *Queries) UpdateRewriteLogQuality(ctx context.Context, arg UpdateRewriteLogQualityParams) error {
	_, err := q.db.Exec(ctx, updateRewriteLogQuality, arg.ID, arg.Quality)
	return err
}
