// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_email_webhook.sql

package sqlc

import (
	"context"
)

const markEmailByProviderID = `-- name: MarkEmailByProviderID :exec
UPDATE email_logs SET status = $2, error = COALESCE($3, error) WHERE provider_id = $1
`

type MarkEmailByProviderIDParams struct {
	ProviderID *string `db:"provider_id" json:"provider_id"`
	Status     string  `db:"status" json:"status"`
	Error      *string `db:"error" json:"error"`
}

// Reflect a Resend delivery event onto email_logs.status (by Resend
// message id). error is only overwritten when a reason is supplied —
// a NULL reason leaves the existing error untouched, mirroring the
// NestJS markByProviderId (which omits error from the UPDATE when the
// detail arg is null).
func (q *Queries) MarkEmailByProviderID(ctx context.Context, arg MarkEmailByProviderIDParams) error {
	_, err := q.db.Exec(ctx, markEmailByProviderID, arg.ProviderID, arg.Status, arg.Error)
	return err
}

const suppressEmail = `-- name: SuppressEmail :exec
INSERT INTO email_suppressions (email, reason) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SuppressEmailParams struct {
	Email  string  `db:"email" json:"email"`
	Reason *string `db:"reason" json:"reason"`
}

// Add an address to the suppression list (idempotent). Mirrors the
// NestJS suppress() orIgnore() → bare ON CONFLICT DO NOTHING.
func (q *Queries) SuppressEmail(ctx context.Context, arg SuppressEmailParams) error {
	_, err := q.db.Exec(ctx, suppressEmail, arg.Email, arg.Reason)
	return err
}
