-- Add 'google' (Gemini) to the ai_providers.type Postgres enum.
--
-- Prod runs with TypeORM synchronize OFF, so new enum values must be added
-- by migration before the app boots with code that can emit them — otherwise
-- inserting/updating a provider with type='google' fails at the DB layer.
--
-- Idempotent: `ADD VALUE IF NOT EXISTS` skips when the value already exists,
-- so re-running is safe. TypeORM names the enum type `<table>_<column>_enum`.
--
-- Gemini is served through the existing OpenAiStrategy (its /v1beta/openai/
-- endpoint is OpenAI wire-compatible); no new strategy or column is needed.
ALTER TYPE ai_providers_type_enum ADD VALUE IF NOT EXISTS 'google';
