#!/usr/bin/env python3
"""Generate the VI unigram dictionary for BOTH clients from ONE source.
Source: tools/wordlist_vi_source.tsv (word<TAB>freq, # comments).
Emits:  android/.../res/raw/wordlist_vi.tsv (verbatim rows)
        ios/.../IME/VietnameseWordList.swift (static let entries: [(String,Int)])
Keeping both generated from one file is the RULE #1 single-source; the
check-vi-wordlist-parity.py guard asserts they never drift."""
import pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]  # DraftRightMobile/
SRC = ROOT / "tools" / "wordlist_vi_source.tsv"
ANDROID = ROOT / "android/app/src/main/res/raw/wordlist_vi.tsv"
SWIFT = ROOT / "ios/DraftRightKeyboardCore/Sources/DraftRightKeyboardCore/IME/VietnameseWordList.swift"

def rows():
    out = []
    for ln in SRC.read_text(encoding="utf-8").splitlines():
        if not ln.strip() or ln.startswith("#"):
            continue
        w, f = ln.split("\t")
        out.append((w, int(f)))
    return out

def main():
    data = rows()
    header = ("# DraftRight Vietnamese word list — frequency-ranked single syllables.\n"
              "# Source: hermitdave/FrequencyWords (OpenSubtitles 2018), CC BY-SA 4.0.\n"
              "# Generated by tools/gen_vi_wordlist.py from tools/wordlist_vi_source.tsv — DO NOT EDIT BY HAND.\n"
              "# Format: word<TAB>frequency.\n")
    ANDROID.write_text(header + "".join(f"{w}\t{f}\n" for w, f in data), encoding="utf-8")
    lines = ["// Generated by tools/gen_vi_wordlist.py — DO NOT EDIT BY HAND.",
             "// Mirror of android/app/src/main/res/raw/wordlist_vi.tsv (byte-parity guarded).",
             "enum VietnameseWordList {",
             "    static let entries: [(word: String, freq: Int)] = ["]
    lines += [f'        ("{w}", {f}),' for w, f in data]
    lines += ["    ]", "}", ""]
    SWIFT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(data)} rows -> {ANDROID.name} + {SWIFT.name}")

if __name__ == "__main__":
    main()
